### ISSUE TITLE
Caching doesn't escape loaded values from cache store

### ISSUE THREAD

**Issue by Imomoi** [apotonick/cells#109]
In Rails 3.2.1 cells doesn't escape cached values after reading them from database.

Our workaround for this issue is `config/initializers/cells_fix.rb`:

    Cell::Base.class_eval do
      def render_state(state, *args)
        rendered_state = super(state, *args)
        return rendered_state.html_safe if rendered_state.respond_to?(:html_safe)
        rendered_state
      end
    end

**Comment by apotonick** [comment]
I close this because we don't do escaping anymore in Cells 4 - only for defined properties, which should make this issue obsolete.
