### ISSUE TITLE
Shortform for render with :locals

### ISSUE THREAD

**Issue by apotonick** [apotonick/cells#137]
The current workflow of assigning variables is tiresome:

```ruby
def show(user, comments)
  @user = user
  @comments = comments

  render
end
```

Alternatively, people do that.

```ruby
def show(user, comments)
  render :locals => {:user => user, ..}
end
```

What about a shortform?

```ruby
def show(user, comments)
  emit :user => user, :comments => comments
end
```

That would make the arguments locals variables. A little bit like `render :partial` works with Rails. The `emit` method is of course just a name, suggestions welcome.

Also, there could be some standard behaviour.

```ruby
class CommentsCell < ..
  def show(arg)
    emit
  end
```

Making `arg` available as `comment` in the view. Ideas?

**Comment by apotonick** [comment]
Do we still want that with Cells 4?

**Comment by PikachuEXE** [comment]
I am already using Concept cell, no need for this :D

**Comment by apotonick** [comment]
This won't be necessary with `ViewModel` anymore and in combination with `Options` (coming soon).
