### ISSUE TITLE
Mounting Cell::Rails

### ISSUE THREAD

**Issue by hipertracker** [apotonick/cells#142]
How to mount a cell inheriting from Cell::Rails instead of Cell::Base? I need Cell:Rails because the cell uses some Rails methods. Can I group all together? I mean: cell's controller, view and also it's css, js and route so it could use it's own path for ajax calls?

**Comment by kikorb** [comment]
I hope is not too late I found that you can do it like this:

```
match "/posts" => proc { |env|
  controller = ActionController::Base.new
  controller.request = ActionDispatch::Request.new(env)

  [ 200, {}, [ Cell::Rack.render_cell_for(:post, :show, controller, controller.request.query_parameters) ]]
}
```

Basically providing an empty controller with the necessary request object

**Comment by apotonick** [comment]
@kikorb Your solution is for Cells 3.x. In Cells 4, this will be as simple as

```ruby
cell(:post, request: request) 
```

or something like that.

**Comment by apotonick** [comment]
I will close this issue as in Cells 4, we don't have any controller dependency anymore.

You can simply do 

```ruby
Song::Cell.new(song).()
```
