### ISSUE TITLE
Caching: the cell's cache is not using template's md5 as part of caching key

### ISSUE THREAD

**Issue by PikachuEXE** [apotonick/cells#188]
Is it possible to specify use the template's md5?
Or do I have to update a version number in caching key everytime I have changed the template?

**Comment by apotonick** [comment]
@PikachuEXE Any help needed here? Or can we close this?

**Comment by PikachuEXE** [comment]
I am using "manual update" an additional key as part of cache key to do this
It kind of works.
Until a better solution is found, I am closing this.

**Comment by musaffa** [comment]
Please we need this feature!

**Comment by PikachuEXE** [comment]
I wonder how to do it
Since the templates to be rendered are dynamic isn't it?

**Comment by apotonick** [comment]
I don't understand this feature. 

* Does it mean the cache key should be the "MD5 sum of the template file" (whatever that means)? 
* How do you know which template will be rendered when computing the cache key?
* What's the purpose? To cache a template until the file changes?

**Comment by musaffa** [comment]
Rails caches templates with `config.action_view.cache_template_loading` on each server restart. So it knows the digested versions of the templates before hand. During cache key generation within a partial, it also uses the digest of that partial file.

```Ruby
# /app/views/projects/_project.html.haml
- cache project do
  %h2= link_to project.name, edit_project_path(project)
  %ul= render partial: 'tasks/task', collection: project.incomplete_tasks
```

If the digest changes due to a modification in the partial file, there will be a cache miss.

**Comment by apotonick** [comment]
Ah, so the MD5 is automatically included in the cache key?

**Comment by musaffa** [comment]
Yes i think so.

The purpose of this feature is that sometimes we only change the templates without modifying of the resources. As cell states bypass render when there's a cache hit, they cannot reflect the changes made in the corresponding templates.

**Comment by apotonick** [comment]
Yeah but how do you know that it's gonna be the `show.haml` file in the versioner? You only know the used template for sure until you run the state.

I have an idea how we can provide that optionally.

**Comment by musaffa** [comment]
Yes we need an option that will do the magic. Before `cache_digest`, the developers were used to include a version number in the cache key after any update in the templates.

**Comment by reneklacan** [comment]
@apotonick Any update on this?

**Comment by PikachuEXE** [comment]
My workaround/solution is:

```ruby
TEMPLATE_FILES_CONTENT_CACHE_KEY = begin
    view_folder_path = File.expand_path("../views", __FILE__)
    file_paths = Dir.glob(File.join(view_folder_path, "**", "*"))

    file_digests = file_paths.map do |file_path|
      ::Digest::MD5.hexdigest(File.read(file_path))
    end

    ::Digest::MD5.hexdigest(file_digests.join(""))
  end
```

But only works if all templates are used and the files are within the same folder
If any of them is in parent cell(s) or different view path, requires another solution

**Comment by reneklacan** [comment]
In my current version I utilized Rails's Digestor like this:

```ruby
class ApplicationCell < Cell::ViewModel
  @@lookup_context = ActionView::LookupContext.new(::Rails.root.join("app/cells"), {})

  protected

  def digest(template)
    ActionView::Digestor.digest(name: template, finder: @@lookup_context)
  end
end
```

```ruby
class BananasCell < ApplicationCell
  cache :show do
    digest("users/bananas/show")
  end
end
```

Not perfect but it's not too ugly...

**Comment by apotonick** [comment]
@reneklacan We could talk to Rails core about changing their API for `Digestor` so it doesn't have to be ugly anymore?
