### ISSUE TITLE
cells doesn't seem to respect `isolate_namespace`

### ISSUE THREAD

**Issue by aaronjensen** [apotonick/cells#198]
If I want to use cells within an engine, they appear to have access to all of the url helpers of the main app even if I do `isolate_namespace`. Is there a way around this? Seems like maybe something that could/should be supported out of the box?

**Comment by apotonick** [comment]
That code is ridiculous. I am not sure if I am gonna support this in Cells 4.

The good thing is we don't have the problem with "wrong" helpers being included into Cells, as you have to explicitely say which helpers you want.

The bad news is we would need a switch where we either include the app's Url helper module, or only the `define_method(:railtie_routes_url_helpers) { railtie.routes_url_helpers }` bullshit one.

Oh man, how I fucking hate Rails and its helper system.

**Comment by sveredyuk** [comment]
I have the same issue... On my regular rails views for correct paths i used `link_to 'Home', mynamespace.root_path`... what i must to do that include this `mynamespace` helper method to my cells ?

**Comment by dreyks** [comment]
I'm using `include Engine.routes.url_helpers`

```ruby
module MySuperEngine
  class MySuperCell < Cell::ViewModel
    include Engine.routes.url_helpers

    def my_super_method
      link_to 'whatever', engine_specific_path_without_any_namespaces_needed
    end
  end
end

**Comment by apotonick** [comment]
Cool. @dreyks, I will document that as this looks like the cleanest way to solve this.
