### ISSUE TITLE
Cells vs. JS driver frameworks, e.g. AngularJS or EmberJS?

### ISSUE THREAD

**Issue by jmuheim** [apotonick/cells#200]
Hey Nick

I really like Cells (although I didn't work with it a lot yet), as it gives me the possibility to create quite interactive widgets with my known and beloved Ruby tools.

On the other hand, I dove into the world of JS MVC frameworks some days ago (namely EmberJS), and now I'm wondering: when should I ever choose Cells over pure JS MVC?

From my small knowledge from both worlds, I can imagine, that it's reasonable to choose Cells for rather static areas in a classic Rails application that's repeated on many pages again and again, so I don't have to code the same HTML structure more than once. As an example, in an application, we always use the same box around some data with buttons etc., which occurs on nearly every page, sometimes more than once. So it's like a frame border or so. For this, Cells is very useful.

For very sophisticated and responsive widgets I'd rather choose EmberJS.

Can you confirm this? Any other thoughts on this issue?

Thank you for creating and maintaining Cells for years already, it definitely is a very cool gem! :+1:

**Comment by apotonick** [comment]
This is a secret but I'm gonna tell you anyway: cells-widget is gonna be all the good parts of Apotomo combined with Cells. I am expecting JS framework integrations from that project. :rocket: :guitar:
