### ISSUE TITLE
Directly using the parent template's context (?) object in cell do strange things

### ISSUE THREAD

**Issue by Iazel** [apotonick/cells#211]
Hello, instead of including all the helpers modules in the ViewModel, I prefer to use the template object crafted by Rails. So, in the template I call:

```haml
= cell(:form, @model).show(self)
```

Notice that `self` is passed to the show method and it's then accessed in the template rendered by this cell through `#helper`.

However, this example code:
```haml
Hello
= helper.form_for(model) do |f|
  = f.text_field :name
World
```

Will result:
```html
Hello
<input type="text" id="model_name" name="model[name]">
<form accept-charset="UTF-8" action="/products" class="new_product" id="new_product" method="post">
<div style="display:none"><input name="utf8" type="hidden" value="✓"><input name="authenticity_token" type="hidden" value="/KYB3haotsmsVO9eaLIxgf+YndBQE9pDKs9nHfT+98s="></div>
</form>
World
```

As you can see, the input is put before the form, while the latter is empty... I haven't enough knowledge of rails internals to understand why this happens. Maybe some problem with the different context? And yet, if this should be the case, I will expect the form to be output _after_ "World"...

Someone have a better guess? :)

**Comment by apotonick** [comment]
The ERB is fixed in cells-erb 0.0.2.
