### ISSUE TITLE
Rails 4: Asset Path

### ISSUE THREAD

**Issue by incorvia** [apotonick/cells#214]
The troubleshooting page says that to get image_tag to return "/assets/image.jpg" instead of "/images/image.jpg" you need to include:  Sprockets::Helpers::RailsHelper.  I believe this doesn't exist in newer versions of sprockets-rails, perhaps it is now:  Sprockets::Rails::Helper?  Anyways.. even including that I am still getting "/images/image.jpg" ... 

    class NavbarCell < Cell::ViewModel
      include Authable
      include Sprockets::Rails::Helper

      def show
        render
      end

    end

What is the correct way to handle this now?

**Comment by apotonick** [comment]
@incorvia I added a test for that here: https://github.com/apotonick/cells/blob/master/test/rails4.2/test/integration/url_helper_test.rb#L32

The cell sits here: https://github.com/apotonick/cells/blob/master/test/rails4.2/test/integration/url_helper_test.rb#L32

As you can see, this is a fully self-encoded Rails app to test Cells. Could you make this test pass/fail? I don't know what your app setup is to make this `/assets` problem pop up. That'll be great for finding what's the problem.

@gavinkflam I can't include them per default since people might not use sprockets. Sorry!

**Comment by PikachuEXE** [comment]
I just delegate `image_tag` to `ActionController::Base.helpers`
It's not OO but it works.
I don't want to touch the rails screwed up helper system.

**Comment by apotonick** [comment]
That is brillant, @PikachuEXE !!! Actually, the fix could be even simpler:

```ruby
class Comment::Cell
  include Uber::Delegates
  delegates :image_tag, :parent_controller
```

**Comment by PikachuEXE** [comment]
`parent_controller` is a magic thing that I didn't know
I won't use it until this is properly documented :D

**Comment by apotonick** [comment]
Goooood boy! It is a stable dependency in cells with Rails.

**Comment by PikachuEXE** [comment]
Still too "magical" for me. (Especially "rails only")
And these gem are meant to remove the "magic" right?

**Comment by apotonick** [comment]
Hahaha! No magic, it's an explicit option getting passed into the cell via the `#concept` helper: https://github.com/apotonick/cells/blob/master/lib/cell/rails.rb#L10

**Comment by PikachuEXE** [comment]
Whatever I use, this is one of the "pitfalls" when using rails.
Worth documenting?

**Comment by apotonick** [comment]
Documented this fix here: http://trailblazerb.org/gems/cells/helpers.html#asset-helpers

**Comment by timoschilling** [comment]
new link from last comment: http://trailblazer.to/gems/cells/helpers.html#asset-helpers

**Comment by bingxie** [comment]
I tried: delegates :parent_controller, :image_tag

But it said: undefined method `image_tag' for #<ProductsController:0x007ffce7c0f260>

I am using Rails 4.2.5

**Comment by apotonick** [comment]
In the controller, you might have to say

```ruby
class ApplicationController < ..
  helper_method :image_tag
```

Please note that this is Rails-specific, and I do not support Rails anymore.

**Comment by bingxie** [comment]
ok, ok, no rails! thanks for you quick response!

**Comment by apotonick** [comment]
Haha, you're good, use Rails, but be prepared for problems like this! :grimacing: 

Does the `helper_method` work for you? Should I add that to docs?

**Comment by bingxie** [comment]
Actually, It doesn't work. :(

**Comment by anaumov** [comment]
Sometimes it works, sometimes don't. Any suggestions?

**Comment by PikachuEXE** [comment]
I always use `::ActionController::Base.helpers.image_tag`
Question/Blame rails for this.

**Comment by apotonick** [comment]
Yepp! Suggestion is to open an issue on Rails- we can't do anything beyond providing a beautiful view layer. Sorry!

**Comment by bingxie** [comment]
thanks @PikachuEXE

**Comment by AndreiMashkov** [comment]
Unfortunately these hacks don't work for me starting from Rails 4.2.5 so I have to move Sprockets environment initialization to application.rb (or to the separate initializer). This snippet helps (after_initialize is crucial here):
```
    config.after_initialize do |app|
      Cell::ViewModel.send(:include, Sprockets::Rails::Helper)

      Cell::ViewModel.assets_prefix       = app.config.assets.prefix
      Cell::ViewModel.assets_environment  = app.assets
      Cell::ViewModel.digest_assets       = app.config.assets[:digest]
      Cell::ViewModel.assets_manifest     = app.assets_manifest
      Cell::ViewModel.resolve_assets_with = app.config.assets.resolve_with

      Cell::ViewModel.precompiled_asset_checker = -> logical_path { app.asset_precompiled?(logical_path) }
    end
```

**Comment by sebabouche** [comment]
@AndreiMashkov :+1: Thanks so much! I couldn't solve this and was sending the whole sprocketed url with `options[:url]`. Dirty dev ^^

**Comment by apotonick** [comment]
We probably could extract a lot of code into a new gem `cells-rails` that takes care of all those nasty hacks?

**Comment by apneadiving** [comment]
Would help to have something to replace `asset_url` as well.
I tend to agree with rails mess described here

**Comment by apotonick** [comment]
Please all use the https://github.com/trailblazer/cells-rails gem, it fixes all of the above problems.

**Comment by PikachuEXE** [comment]
Why this project is not under `trailblazer`? :)
