### ISSUE TITLE
Cells 4.0 can't support block over two-depths.

### ISSUE THREAD

**Issue by wildjcrt** [apotonick/cells#246]
Here is my test app in Rails 4.1. Clone [Repo](https://github.com/wildjcrt/testcells41) and then open `http://localhost:3000/posts/1`.
Master branch works fine, but checkout out to branch `two-depths-block`, it will be broken.

In `cells/post_cell.rb`

    def link_2d(args)
      @post = args[:post]
      render
    end

In `cells/post/link_2d.erb`

    <% 5.times do %>
      <%= link_to("posts/#{@post.id}") do %>
        <%= @post.title %>
      <% end %>
    <% end %>

In view

    <%= cell(:post).call(:link_2d, :post => @post) %>

The error message shows:

    Started GET "/posts/1" for 127.0.0.1 at 2014-10-22 11:30:22 +0800
      ActiveRecord::SchemaMigration Load (6.9ms)  SELECT "schema_migrations".* FROM "schema_migrations"
    Processing by PostsController#show as HTML
      Parameters: {"id"=>"1"}
      Post Load (17.3ms)  SELECT  "posts".* FROM "posts"  WHERE "posts"."id" = ? LIMIT 1  [["id", 1]]
    checking app/cells/post/link_good.erb
    checking app/cells/post/link_2d.erb
      Rendered posts/show.html.erb within layouts/application (58.4ms)
    Completed 500 Internal Server Error in 164ms

    ActionView::Template::Error (undefined local variable or method `_erbout_tmp' for #<PostCell:0x007ff136224898>):
        14:   <br><br>
        15:   This will be fail in two-depths block.
        16:   Error msg: "undefined local variable or method `_erbout_tmp'".
        17:   erb cells: <%= cell(:post).call(:link_2d, :post => @post) %>
        18: </p>
        19:
        20: <%= link_to 'Edit', edit_post_path(@post) %> |
      app/cells/post/link_2d.erb:5:in `block (2 levels) in singleton class'
      app/cells/post/link_2d.erb:1:in `times'
      app/cells/post/link_2d.erb:1:in `block in singleton class'
      app/cells/post/link_2d.erb:-5:in `instance_eval'
      app/cells/post/link_2d.erb:-5:in `singleton class'
      app/cells/post/link_2d.erb:-7:in `__tilt_70336997987060'
      app/cells/post_cell.rb:13:in `link_2d'
      app/views/posts/show.html.erb:17:in `_app_views_posts_show_html_erb__3566755739723593007_70336986208940'

      Rendered /Users/wildjcrt/.rvm/gems/ruby-2.1.3/gems/actionpack-4.1.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.2ms)
      Rendered /Users/wildjcrt/.rvm/gems/ruby-2.1.3/gems/actionpack-4.1.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.1ms)
      Rendered /Users/wildjcrt/.rvm/gems/ruby-2.1.3/gems/actionpack-4.1.1/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (18.8ms)

**Comment by apotonick** [comment]
This is fixed in cells-erb 0.0.2.
