### ISSUE TITLE
Cells 4.0 should have wrapper in block method like link_to.

### ISSUE THREAD

**Issue by wildjcrt** [apotonick/cells#247]
Here is my test app in Rails 4.1. Clone [Repo](https://github.com/wildjcrt/testcells41) and then open `http://localhost:3000/posts/1`.
Master branch works fine, but checkout out to branch `link_to_without_wrapper`, it will be broken.

In `cells/post_cell.rb`

    def link_good(args)
      @post = args[:post]
      render
    end

In `cells/post/link_good.erb`

    <%= link_to "posts/#{@post.id}" do %>
      <%= @post.title %>
    <% end %>

In view

    <%= cell(:post).call(:link_good, :post => @post) %>

The error message shows:

    Started GET "/posts/1" for 127.0.0.1 at 2014-10-22 11:34:49 +0800
      ActiveRecord::SchemaMigration Load (0.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"
    Processing by PostsController#show as HTML
      Parameters: {"id"=>"1"}
      Post Load (0.2ms)  SELECT  "posts".* FROM "posts"  WHERE "posts"."id" = ? LIMIT 1  [["id", 1]]
    checking app/cells/post/link_good.erb
      Rendered posts/show.html.erb within layouts/application (9.2ms)
    Completed 500 Internal Server Error in 28ms

    SyntaxError (app/cells/post/link_good.erb:1: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
    _erbout <<  link_to "posts/#{@post.id}" do ;_erbou...
                         ^
    app/cells/post/link_good.erb:1: syntax error, unexpected keyword_do, expecting keyword_end
    ... link_to "posts/#{@post.id}" do ;_erbout_tmp = ''; _erbout_t...
    ...                               ^
    app/cells/post/link_good.erb:7: syntax error, unexpected keyword_ensure, expecting keyword_end
    app/cells/post/link_good.erb:11: syntax error, unexpected keyword_end, expecting end-of-input
    end;end;end;end
                   ^):
      app/cells/post_cell.rb:8:in `link_good'
      app/views/posts/show.html.erb:13:in `_app_views_posts_show_html_erb__2586495935869945092_70214936484000'

      Rendered /Users/wildjcrt/.rvm/gems/ruby-2.1.3/gems/actionpack-4.1.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (0.9ms)
      Rendered /Users/wildjcrt/.rvm/gems/ruby-2.1.3/gems/actionpack-4.1.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.9ms)
      Rendered /Users/wildjcrt/.rvm/gems/ruby-2.1.3/gems/actionpack-4.1.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.1ms)
      Rendered /Users/wildjcrt/.rvm/gems/ruby-2.1.3/gems/actionpack-4.1.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (21.7ms)

**Comment by incorvia** [comment]
I can't get a link_to block to work with or without a wrapper.. same error...

**Comment by seuros** [comment]
add `cells-haml` in your Gemfile.

**Comment by incorvia** [comment]
I'm not using haml

**Comment by seuros** [comment]
What are you using?

**Comment by incorvia** [comment]
Erb, like in the example above.

**Comment by seuros** [comment]
Try with `cells-erb`

**Comment by incorvia** [comment]
Thanks for the suggestion, but that did not works.. not sure what's up...

**Comment by incorvia** [comment]
In fact no block seems to work (I'm using Master btw).. so

    <%= content_for :test do %>
      <p>hello</p>
    <% end %>

**Comment by incorvia** [comment]
To be clear for the following template
 
    <%= content_for("/") do %>
      <p>hi</p>
    <% end %>

I get the error

app/cells/navbar/show.erb:1: syntax error, unexpected ')' _erbout << ( content_for("/") do ).to_s; _erbout << ' ^ app/cells/navbar/show.erb:8: syntax error, unexpected keyword_ensure, expecting ')' app/cells/navbar/show.erb:10: syntax error, unexpected keyword_end, expecting ')'

**Comment by apotonick** [comment]
This is now a confirmed bug in cells-erb and cells-haml. I am closing this as we have duplicate issues.
