### ISSUE TITLE
undefined method `is_haml?' when using block helpers

### ISSUE THREAD

**Issue by mbajur** [apotonick/cells#253]
Hello!
It seems that cells don't want to allow me to use html helpers with block content. For example, the following code works great:

    = link_to 'Home', root_path

While the next example fails with exception:

    = link_to root_path do
      span Home

The exception is: `undefined method 'is_haml?' for #<SomeCellName:0x007f90adc80650>`
I'm using cells at HEAD and rails 4.1.5.

Thanks

**Comment by apotonick** [comment]
This is fixed in cells-haml 0.0.2. Is that still a problem with slim?

**Comment by mbajur** [comment]
I'm gonna check that soon
