### ISSUE TITLE
Problem with slim engine

### ISSUE THREAD

**Issue by MaximAbramchuck** [apotonick/cells#255]
When I load my page with views using cells, I have a great trace of errors "Option :escape_html is not supported by Slim::Engine" in the server log. It looks very ugly and disappointing. I haven't found solution for this trouble in google.

**Comment by incorvia** [comment]
Also seeing this issue.. I guess the line is in templates.rb

          Tilt.new("#{base}/#{prefix}/#{view}", :escape_html => false, :escape_attrs => false)

Is attempting to use Tilt with cells-slim when slim doesn't support these options.. Obviously you know this but just posting here for posterity..

**Comment by incorvia** [comment]
So slight modification.. my issue is I would see the warnings:

    Slim::Engine: Option :escape_html is invalid
    Slim::Engine: Option :escape_attrs is invalid

Turns out I only see them when using 'slim-rails'.. switching to 'slim' directly and I no longer see these warnings...  good enough for me for now.

**Comment by apotonick** [comment]
I will come back to Cells the next week and then we will fix it.

**Comment by porbas** [comment]
@apotonick Hi, any progress with this? How can I help?

**Comment by apotonick** [comment]
Is slim working OK so far? Is it "just" this warning? Will look into it once I know more from you! :wink:

**Comment by porbas** [comment]
Yes, its "just" this warning cluttering my tests output :(
No other problems with cells+slim

**Comment by apotonick** [comment]
Hey @porbas can you do me a favour and convert all those files in here to correct slim? https://github.com/trailblazer/cells-slim/tree/master/test/dummy/app/cells/song

**Comment by porbas** [comment]
Templates converted to slim: porbas/cells-slim@57a1306950076a41823c1d403cc86b55ff35fe26
To run tests I had to get earlier version of lib/cells/slim.rb and include ActionView and routes helpers in songs/cell.rb (not in commit)

There are problems with capturing and html_escaping.

**Comment by seuros** [comment]
can you pr it ?

**Comment by apotonick** [comment]
All tests passing now, released cells-slim-0.0.2. Please test and report bugs it the cells-slim repo. Thaaanks! :beers:
