### ISSUE TITLE
cells does not play well with better_errors

### ISSUE THREAD

**Issue by mbajur** [apotonick/cells#258]
I'm using cells and better_errors in the same app and i have encountered a strange behaviour. I'm not sure if that's better_errors or cells fault but i decided to start from cells.

Basically, if there is something wrong in my cells view file (for example i'm trying to use undefined variable), the app throws the following error:

	(erubis:4: syntax error, unexpected tIDENTIFIER, expecting end-of-input
	...XmlHelper.escape_xml  exception.type ; _buf << ' at '; _buf ...
	...                               ^
	erubis (2.7.0) lib/erubis/evaluator.rb:65:in `eval'
	erubis (2.7.0) lib/erubis/evaluator.rb:65:in `result'
	/Volumes/HDD/Users/michal/.rvm/gems/ruby-2.1.2/bundler/gems/better_errors-f4308e6b4a5a/lib/better_errors/error_page.rb:30:in `render'
	/Volumes/HDD/Users/michal/.rvm/gems/ruby-2.1.2/bundler/gems/better_errors-f4308e6b4a5a/lib/better_errors/middleware.rb:96:in `show_error_page'
	/Volumes/HDD/Users/michal/.rvm/gems/ruby-2.1.2/bundler/gems/better_errors-f4308e6b4a5a/lib/better_errors/middleware.rb:88:in `rescue in protected_app_call'
	/Volumes/HDD/Users/michal/.rvm/gems/ruby-2.1.2/bundler/gems/better_errors-f4308e6b4a5a/lib/better_errors/middleware.rb:84:in `protected_app_call'
	/Volumes/HDD/Users/michal/.rvm/gems/ruby-2.1.2/bundler/gems/better_errors-f4308e6b4a5a/lib/better_errors/middleware.rb:79:in `better_errors_call'
	/Volumes/HDD/Users/michal/.rvm/gems/ruby-2.1.2/bundler/gems/better_errors-f4308e6b4a5a/lib/better_errors/middleware.rb:57:in `call'
	actionpack (4.1.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
	actionpack (4.1.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
	railties (4.1.5) lib/rails/rack/logger.rb:38:in `call_app'
	railties (4.1.5) lib/rails/rack/logger.rb:20:in `block in call'
	activesupport (4.1.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
	activesupport (4.1.5) lib/active_support/tagged_logging.rb:26:in `tagged'
	activesupport (4.1.5) lib/active_support/tagged_logging.rb:68:in `tagged'
	railties (4.1.5) lib/rails/rack/logger.rb:20:in `call'
	request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
	actionpack (4.1.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
	rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
	rack (1.5.2) lib/rack/runtime.rb:17:in `call'
	activesupport (4.1.5) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
	rack (1.5.2) lib/rack/lock.rb:17:in `call'
	actionpack (4.1.5) lib/action_dispatch/middleware/static.rb:64:in `call'
	rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
	railties (4.1.5) lib/rails/engine.rb:514:in `call'
	railties (4.1.5) lib/rails/application.rb:144:in `call'
	rack (1.5.2) lib/rack/lock.rb:17:in `call'
	rack (1.5.2) lib/rack/content_length.rb:14:in `call'
	rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
	/Volumes/HDD/Users/michal/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
	/Volumes/HDD/Users/michal/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
	/Volumes/HDD/Users/michal/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

And that happens only when better_errors are present in my Gemfile. If that's rather better_errors relevant, please let me know and i'll create  a separate issue on their github profile. Thanks!

**Comment by apotonick** [comment]
This is fixed with cells-erb 0.0.2.
