### ISSUE TITLE
self_contained and view helper "cell" not working together

### ISSUE THREAD

**Issue by byu** [apotonick/cells#271]
4.0.0.beta2:

if I make a `app/cells/comment/cell.rb self_contained` cell, I can render just fine by doing `Comment::Cell.new(controller, @comment).show`.

But in some other controller's view, I try using: 
<%= cell(:comment, @comment) %>

the http request errors out with `uninitialized constant CommentCell`.

It looks like class_from_cell_name in view_model.rb has the line:

 `"#{name}_cell".classify.constantize`

**Comment by apotonick** [comment]
You need to use the `#concept` helper instead of `#cell`. This is because you use the new, cooler, better, beautifuler and sexier concept (Trailblazer) naming style `Comment::Cell`.
