### ISSUE TITLE
not loading cells from rails engine

### ISSUE THREAD

**Issue by dreyks** [apotonick/cells#280]
Hi there.

I have an app with an engine in it. That engine has cells. All works nice out of the box for the cells 3.x but on 4.0.0.beta2 I get `Template missing: view: `show.erb` prefixes: ["app_block"] view_paths:["app/cells"]` when calling `<%= cell(:app_block, whatever) %>`.
None of the ways mentioned both in readme and `Cell::Engines` seem to work. Just can't tell cells that engine cells must also be accounted for.

**Comment by dreyks** [comment]
[view_model.rb#L19](https://github.com/apotonick/cells/blob/master/lib/cell/view_model.rb#L19) sais just `self.view_paths = ["app/cells"]` which is wrong if the cell is inside an engine

**Comment by alihuber** [comment]
Same problem here. I'm trying to use Trailblazer's concept-oriented layout and getting the same error for the view path: `Template missing: view: 'tile.slim' prefixes: ["my_engine/namespace/views"] view_paths:["app/concepts"]`. I'm calling the cell like this: `concept("my_engine/namespace/cell", @model).call(:tile)` and it inherits from `Cell::Concept`.  
The way described [in the engines.rb file](https://github.com/apotonick/cells/blob/master/lib/cell/engines.rb) to alter the `view_paths`-setting seems not to work, I can add any path I want.

**Comment by dreyks** [comment]
the thing is that engines.rb seems to be outdated, cause it uses `Cell::Rails` which isn't even present in cells 4.0

the immediate workaround for me is to use 

`render view: :show, base: ["#{path_to_my_engine}/app/cells"]` in my `show` action

**Comment by apotonick** [comment]
Hi guys, sorry for the late reply. I haven't implemented support for engines in Cells 4, yet. But as you can see :wink: it's on our "TODO" :wink: list :wink: https://github.com/apotonick/cells/wiki/Cells-4.0

I've been traveling to conferences the last 12 weeks and hoping to catch up soon and push out a nice and fast and clean Cells 4.0.

**Comment by apotonick** [comment]
Here's how to fix it from 4.0.0.beta4 onwards: http://trailblazerb.org/gems/cells/render.html#view-paths

I am working on setting the `view_paths` in an engine cell automatically just now, but in the meantime, this will work.

```ruby
class MyEngine::Cell < ..
  view_paths << "/path/to/my/engine/app/cells"
```

As noted in the doc, do as follows to find out how the engine cell finds its views.

```ruby
puts MyEngine::Cell.prefixes
```

Everything here depends on your feedback, I am not using cells in engines at the moment and need your help!! :beers:

**Comment by apotonick** [comment]
What about the following convention?

In your railtie, set your cell's view path.

```ruby
class MyEngine < Rails::Engine
  Cell.view_paths << File.expand_path("../app/cells", __FILE__)
end
```

Does that work? Can we also use `MyEngine.root`? An example app would be great.

I am not planning to integrate that into Cells itself as this implies a lot of hacking with Rails/Engines internals, which is absolutely not how I plan to spend the rest of the day. :wink: 

If you get the chance, please provide some feedback, how you managed to get it working. Much appreciated! :heart:

**Comment by bmcdaniel11** [comment]
@dreyks you can get your engine to work by setting a single element in the view paths array to be your engine cell view path.

So for example:
MyEngineCell < Cells::ViewModel
  self.view_paths = ["#{MyEngine.root}/cells"]


I would recommend having a base cell of some sort to put that in and just extend that. Currently this solution is working for me but I have not tried inheriting that base cell from outside the engine, I.e. the parent app, so I'm not sure if that works since you are technically overriding the original view path of "app/cells"

**Comment by bmcdaniel11** [comment]
Sorry for the lack of editing, I'm using a phone :P

**Comment by bmcdaniel11** [comment]
@apotonick just to note, you can't append the view path from the engine cell because only the first of the base paths is being recognized, as shown via the referenced pull request. Jamis' solution was to iterate over all the base paths, but as we discussed, that isn't very efficient. Just telling cells one place to look for cells in the parent app and cells in the engine would be better.

**Comment by alihuber** [comment]
I tried out above solutions, they all work. I made this little demo app (https://github.com/alihuber/engine_cells) to try them out, as you can see adding to the view paths in the Cell works, and also adding  
`Cell::Concept.view_paths << File.expand_path("#{MyEngine::Engine.root}/app/concepts", __FILE__)`
somewhere in either `lib/my_engine.rb` or `lib/my_engine/engine.rb`.

**Comment by apotonick** [comment]
Cool, thanks @alihuber now I can see if I can abstract that. Thanks! :heart: 

@bmcdaniel11 You can also append the `view_paths` of the engine cell, when rendering this cell (e.g. `MyEngine::Cell` it first looks in `app/cells` for overridden views, then in the canonical engine dir.

You have to make sure you use `cells-4.0.0.beta4` or cells/master, @bmcdaniel11, did you do that? Thanks for your help.

**Comment by apotonick** [comment]
It works great, thanks @alihuber :beer:   and @bmcdaniel11.

@alihuber I had to add the `cells-erb` gem to the app's `Gemfile` in order to make the engine cell rendering in the application work.

I've documented cells in engines here: http://trailblazerb.org/gems/cells/engine.html

**Comment by apotonick** [comment]
BTW, I'm thinking about a `::namespace` method in line with what we got in Reform and Trailblazer.

```ruby
module MyEngine
  class Song::Cell < Cell::ViewModel
    namespace MyEngine
  end
end 
```

This will strip the `MyEngine` from the cell's prefix, and basically allow to structure your views like this.

```
my_engine/app/concepts/song/views
```

**Comment by bmcdaniel11** [comment]
@apotonick, sorry, I had not tried appending the view path with 4.0.0.beta4, I was out of town during the weekend and was using 4.0.0.beta3 still. Good to know it works on beta4, thanks!

**Comment by jhblacklock** [comment]
I have had a similar issue with rendering engine cell partials when upgrading to 4.1.1.

```
require "cell/partial"
class BaseCell < Cell::ViewModel
  self.view_paths << "#{::Store::Frontend::Engine.root}/cells"
...
end
```

render code
```
 = render partial: 'store/coupon_codes/coupon_code', locals: { coupon_code: my_reward }
```

ERROR
```
Template missing: view: `_coupon_code.haml` prefixes: ["app/cells/store/coupon_codes", "/Users/jacksonblacklock/Sites/store/frontend/cells/store/coupon_codes"]
```

view_paths array has the correct path of my partial and I have tried implementing with a view call instead resulting in a similar error.

**Comment by TheFlow0360** [comment]
@apotonick Is there any documentation for engines that's still available? The cells engine page doesn't exist on the new website...

**Comment by apotonick** [comment]
http://trailblazer.to/gems/cells/rails.html#engine-cells
