### ISSUE TITLE
Name of constant confusing

### ISSUE THREAD

**Issue by KirillMitskevich** [apotonick/cells#281]
Hello :smiley: !
I have this file structure
```bash
FoxCanFly@MacBook-Pro-Kirill:~/work/my_project/app/concepts% tree
.
├── admin
│   └── product
│       ├── cell.rb
│       └── views
│           └── partials
-|-
├── product
│   ├── assets
│   ├── cell.rb
│   └── views
│       ├── partials
│       │   ├── control.slim
│       │   ├── table.slim
│       │   └── table_body.slim
│       └── show.slim
```
_app/concepts/admin/product/cell.rb_
```ruby
class Admin::Product::Cell < Product::Cell
end
```
_app/admin/products_controller.rb_
```ruby
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy]
  before_action :authorize_product

  def index
    @products = Product.includes_all.reverse_all.page(params[:page]).per(10)
  end
```

**screen of the exception**
http://dropmefiles.com/Amh3n

I can fix this using _::Product_ instead of _Product_. But I think it's awful solution.

P.s _Product_ it's my model name.

Thnx)

**Comment by apotonick** [comment]
Hey, I can't see the exception anymore. What exactly is the problem? I don't think that using `::Product` is a wrong thing to do - namespacing and finding constants is still a problem in Ruby :/

**Comment by apotonick** [comment]
This is fixed in the new trailblazer/master initializer: first, the model is loaded, then operation, then cell.
