### ISSUE TITLE
ERB output_buffer errors when embedded in coffee-script

### ISSUE THREAD

**Issue by samstickland** [apotonick/cells#285]
Hi,

I've just upgraded cells and cells-erb to 4.0.0.beta5 and 0.0.3 respectively and it's giving me problems when ERB is included in a coffee-script asset:

```
  1) session management contractor can change password
     Failure/Error: signin(user.email, user.password)
     ActionView::Template::Error:
       undefined local variable or method `output_buffer' for #<#<Class:0x00000006fa1328>:0x00000008b124e0>
         (in /home/dev/hubbadoproto/app/assets/javascripts/contractors.js.coffee.erb)
     # ./app/assets/javascripts/contractors.js.coffee.erb:1:in `block in singleton class'
     # ./app/assets/javascripts/contractors.js.coffee.erb:-1:in `instance_eval'
     # ./app/assets/javascripts/contractors.js.coffee.erb:-1:in `singleton class'
     # ./app/assets/javascripts/contractors.js.coffee.erb:-3:in `__tilt_7444880'
     # ./app/views/layouts/application.html.erb:8:in `_app_views_layouts_application_html_erb__2709517993480273365_37925740'
     # ./spec/helpers/session_helpers.rb:21:in `signin'
     # ./spec/features/session_spec.rb:127:in `test_change_password'
     # ./spec/features/session_spec.rb:144:in `block (2 levels) in <top (required)>'
```

I get similar errors anytime I use a controller that has a js.coffee.erb file. Interestingly it seems to happen even before any cells have been used.

The monkey patch I had in place for a output_buffer issue in cells-erb-0.0.1 does nothing to help with this issue (see https://github.com/apotonick/cells/issues/275)

Sam

**Comment by apotonick** [comment]
Thanks, I was excepting this to happen at some point :) We use Erbse for ERB in Cells, which uses Tilt, and sprockets use Tilt as well (instead of ActionView, which doesn't make sense at all, but, welcome to Rails). Sprockets now uses our ERB which is not compatible with Rails again.

**Comment by samstickland** [comment]
I've tried to replicate this in a small test  project but so far I've been
unable to. I'll let you know how I get on.

**Comment by apotonick** [comment]
No need to do that @samstickland - I know exactly where the problem lies.

**Comment by samstickland** [comment]
In that case I shall leave it in your capable hands :)

**Comment by apotonick** [comment]
I was able to provoke that problem very easily and will fix it in the next 12 hrs. :beers:

**Comment by samstickland** [comment]
OK, perfect :) Btw, there's no need to rush on my account, I can continue
using the previous version for now.

2015-06-03 10:14 GMT+01:00 Nick Sutterer <notifications@github.com>:

**Comment by apotonick** [comment]
This is fixed now in cells/master and cells-erb/master.

However, be warned that there's a bug in sprockets: I was able to reproduce this error in a VANILLA rails 4.2.1 app with the following `application.js.erb` file.

```
/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS and SCSS file within this directory, lib/assets/stylesheets, vendor/assets/stylesheets,
 * or any plugin's vendor/assets/stylesheets directory can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the bottom of the
 * compiled file so the styles you add here take precedence over styles defined in any styles
 * defined in the other CSS/SCSS files in this directory. It is generally better to create a new
 * file per style scope.
 *
 *= require_tree .
 *= require_self
 */

<% capture do %>

<% end %>
```

**Comment by apotonick** [comment]
The way I solved this is very straight-forward: we do not register our templates with Tilt anymore and directly access `Cell::Erb::Template` and so on, so Tilt has no idea about us anymore. Everything breaking in a non-cell is _not_ cell's fault.

**Comment by sps196** [comment]
Thanks Nick, all my tests are passing again now.
