### ISSUE TITLE
`invoke` is undefined in cell tests

### ISSUE THREAD

**Issue by saturnflyer** [apotonick/cells#286]
It looks like the `invoke` method was removed in a recent commit. The generated tests maintain a call to this.

Here's how I'm working around it.

I made a helper for my cell tests
```ruby
require 'rails-dom-testing'
module RenderHelper
  include Rails::Dom::Testing::Assertions::SelectorAssertions
  
  def document_root_element
    @html_document.root
  end
  
  def render_cell(name, model:, action: :show)
    @html_document = Nokogiri::HTML::Document.parse(cell(name, model).send(action))
  end
end

Cell::TestCase.send :include, RenderHelper
```

Then my test looks like this

```ruby
require 'test_helper'
require 'render_helper'

class FirmCellTest < Cell::TestCase
  it "shows the logo if the model has one" do
    render_cell(:firm, model: Firm.new, action: :logo)
    assert_select 'img'
  end
end
```

I'd love some guidance on the intended path for testing cell rendering.

**Comment by apotonick** [comment]
Hey Jim, good to see you here. I hope you've upgraded to Cells 4. Many things have changed and got simpler.

`TestCase#invoke` is now simply `cell`: http://trailblazerb.org/gems/cells/testing.html

I will update the README as soon as I get to it haha! Cheers from Oz my friend, and let me know if that works for you! :heart: 

PS: How's Lotus going? :laughing:

**Comment by apotonick** [comment]
BTW if Capybara is loaded, Cells will automatically wrap the output from `#call` in a matchable object. No need for Nokogiri.

**Comment by sauy7** [comment]
@apotonick Gentle reminder: The unit_test.rb.erb generator template will need changing too.

**Comment by saturnflyer** [comment]
I'm using Cells 4.0.0.beta5

I'm not using Capybara, but I'll look into that. Agreed with @sauy7, the generated tests lead me down the path looking for `invoke`

Lotus: :+1: of course
