### ISSUE TITLE
`image_tag` causes "undefined method `request' for nil:NilClass"

### ISSUE THREAD

**Issue by kevinansfield** [apotonick/cells#287]
Using the `image_tag` helper inside a cell causes an error to be thrown from this line: https://github.com/rails/rails/blob/4-2-stable/actionview/lib/action_view/helpers/asset_url_helper.rb#L203

Adding the following to my cell fixes the issue:

```
private
def request
  false
end
```

Not sure if this is expected or not but thought I'd make an issue in case anyone else runs into it!

**Comment by kevinansfield** [comment]
Oh, and also the code from https://github.com/apotonick/cells/issues/214 so you get `/assets` with the digest instead of `/images`

```
include Sprockets::Rails::Helper

self.assets_prefix = Rails.application.config.assets.prefix
self.assets_environment = Rails.application.assets
self.digest_assets = Rails.application.config.assets[:digest]
```

**Comment by apotonick** [comment]
@kevinansfield Are you sure you were using the RC1? The delegation is fixed there. If yes, how do you invoke your cell? What helpers are mixed in?

I've added a test to show this works (usually), so closing this until we have a failing test.

**Comment by kevinansfield** [comment]
Confirmed on RC1. I was using it in a draper decorator class like this:

```
  def avatar_tag(options={})
    AvatarCell.(object).(:show, options)
  end
```

I realised I hadn't completed my refactor so I've now removed that helper and replaced all uses with direct calls to `cell('avatar')` - when using the `cell` helper directly the `def request` fix isn't needed.

**Comment by apotonick** [comment]
Thanks Kevin!

When you instantiate the cell yourself, you also have to pass in the controller manually, which carries all the url madness.

**Comment by kevinansfield** [comment]
Ok, that makes sense, thanks!

**Comment by StefanWallin** [comment]
How would you pass a controller to a cell initialized within a controller?

**Comment by apotonick** [comment]
The controller is passed automatically into cells and propagated from there to nested cells.

It's available as `Cell#parent_controller`.
