### ISSUE TITLE
Template lookup does not work for Rails engines

### ISSUE THREAD

**Issue by gregorw** [apotonick/cells#293]
When developing a Rails engine, the server is started from `spec/dummy` or `test/dummy`. However, the view lookup expects the root directory. 

See https://github.com/apotonick/cells/blob/master/lib/cell/templates.rb#L24:
`return unless File.exists?("#{prefix}/#{view}")`

Here, `prefix` is something like `app/cells/mycell`, but `Dir.pwd` is `spec/dummy`. So, the view template in `app/cells/mycell/show.slim` is never found.

**Comment by apotonick** [comment]
This is documented here: http://trailblazerb.org/gems/cells/engine.html

**Comment by gregorw** [comment]
Very helpful. Thanks!

**Comment by apotonick** [comment]
:wink:
