### ISSUE TITLE
undefined method `template_options_for'

### ISSUE THREAD

**Issue by EppO** [apotonick/cells#295]
Hi,

using Cells 4.0, I get this error
```ruby
undefined method `template_options_for' for #<TeamMenuCell:0x007fe23aa0b968>
```
Here is the (very simple) code:
```ruby
class TeamMenuCell < Cell::ViewModel
  def show
    render
  end
```
which is called in that view like this:
```ruby
<%= cell(:team_menu, @team, disabled: "thumbnails")  %>
```

Reading the code, I assume ``template_options_for`` is a support method provided by the template engine, as I'm using ERB, is there any incompatibility with it? Or maybe I'm missing something.
Also, after reading the documentation, I have hard time to know how to properly name my cell, should I use ``Comment::Cell`` like in the Cell class section or ``CommentCell`` like in the Properties section.

**Comment by samstickland** [comment]
Have you installed the cells-erb gem?

2015-06-22 20:43 GMT+01:00 Florent Monbillard <notifications@github.com>:

**Comment by apotonick** [comment]
https://github.com/apotonick/cells/#installation :wink:

**Comment by apotonick** [comment]
Thanks @EppO for pointing out the naming inconsistency. I will use the view model naming style throughout the README, the concept style and the benefits are well documented in the Trailblazer book in the Cells chapter. :+1:

**Comment by EppO** [comment]
I feel ashamed of myself... Didn't read the README carefully enough after upgrading from Cells 3.x
Thank you for pointing out my mistake.

**Comment by apotonick** [comment]
Thanks to you for spotting the README inconsistency! Did you see your mention in the commit? :wink: The Installation section is kinda hidden, maybe we should move it up?

**Comment by EppO** [comment]
Yeah I've seen it :)
I would definitely put the Installation chapter before the Usage one, and I'm willing to do it to redeem myself.

**Comment by apotonick** [comment]
I find that the introduction reads very well and a long Introduction interrupts the flow, though?

**Comment by EppO** [comment]
I'm maybe wrong but I think that when you land in cells github page, you already know what you want because you read a blog post about it or you used cells 3.x, so what you're looking for is a quick working setup to start playing with cells. But I agree that all depends on what role you want this github page to fulfill.

**Comment by EppO** [comment]
And links to blog posts in a resources section like the book for example could be a useful option for someone looking for a good introduction to cells.

**Comment by apotonick** [comment]
Good idea about the resource links, even though, I would like people to buy the book. :wink: 

Yeah, true, it's a hard thing to figure out. 50% expect your README to be an awesome introduction with code samples, and the other 50% wants it to be  full-blown documentation covering the entire API, and the other 50% expect both of it plus a complete wiki.

I'm one of the first group: when I browse gems, I check the README and if I can't find instant code snippets to understand (I mostly don't even really read text) I "lose interest" and might move on.

Maybe be can leave the generator section where it was and move just Installation further up?
