### ISSUE TITLE
Missed authenticity_token for form_tag

### ISSUE THREAD

**Issue by opti** [apotonick/cells#296]
Hi,
I'm trying to upgrade my cells to 4.0 and run into the following problem.

It looks like `form_tag` helper doesn't add `authenticity_token` into the form.

#### Here is my concept:

**concepts/example/cell.rb**
```ruby
class Example::Cell < Cell::Concept
  include ActionView::Helpers::FormTagHelper

  property :variant_id

  def show
    render
  end
end
```

**concepts/example/views/show.erb:**

```erb
<%= form_tag example_path do %>
  <%= hidden_field_tag :variant_id, variant_id %>
  <%= submit_tag "Submit" %>
<% end %>
```

**result**

```html
<form action="/example/path" accept-charset="UTF-8" method="post">
  <input name="utf8" type="hidden" value="✓">
  <input type="hidden" name="variant_id" id="variant_id" value="42">
  <input type="submit" name="commit" value="Submit">
</form>
```

But, if I render the same form outside of the concept on the same page, it renders `authenticity_token`.

```erb
<%= concept("example/cell", @object).call %>

<%= form_tag example_path do %>
<% end %>
```

**result**
```html
<form action="/example/path" accept-charset="UTF-8" method="post">
  <input name="utf8" type="hidden" value="✓">
  <input type="hidden" name="authenticity_token" value="PC0Ubh8cKkCa1Tal3rLtIoXXlHK6FocRWX4Q7S5IR9pbb+S+wOx64dbjU9y6GN94C54dCFlg1RiOUg==">
</form>
```

Stack:

rails 4.2.2
trailblazer 0.2.2
cells 4.0.0
cells-erb 0.0.5

Any ideas?
Thanks

**Comment by apotonick** [comment]
Yeah, I haven't implemented that, yet, as it's extremely coupled to the controller. The cell has to ask the controller for the token and then tell the form builder about it - let me have a look now, that I have "more time". :grin:

**Comment by opti** [comment]
Thanks!

**Comment by apotonick** [comment]
Can you try adding the following to `lib/cell/rails.rb`, line 41?

```ruby
    included do
        extend Uber::Delegates
        delegates :parent_controller, :session, :params, :request, :config, :env, :url_options
        # forgery protection. ADD THIS:
        delegates :parent_controller, :protect_against_forgery?, :form_authenticity_token
      end
```

And remove the `protect_against_forgery?` method?

**Comment by opti** [comment]
Sorry, was away from the computer to try it out.

Just upgraded, works perfectly! Thank you @apotonick
