### ISSUE TITLE
prefixes path for engines

### ISSUE THREAD

**Issue by Vorob-Astronaut** [apotonick/cells#302]
Yo, Yo, @apotonick 
I started using cells with engines.
 My engine name is `Core::Cells`, with this file structure:
```
/app/concepts/core/cells
    ├── asd
    │   ├── views
    │   │   └── show.slim
    │   ├── cell.rb
    │   └── assets
    │       └── asd.scss
    └── application
        └── cell.rb
```
_*/core/cells* here is a isolate_namespace_

And when I want to render my _asd_ cell I have an error:
```
Template missing: view: `show.slim` prefixes: ["app/concepts/cores/asd/cell/views", "app/concepts/cores/application/cell/views"]
```

I fix it in this way:
```ruby
module Core::Cells
  class Application::Cell < Cell::Concept
    self_contained!

    def self.prefixes
      class_name = name.split('::')[-2].downcase
      super + ["#{Core::Cells::Engine.root}/app/concepts/core/cells/#{class_name}/views"]
    end
  end
end
```

I think, it's a bad solution.
What do you think about it?

P.s _I can try to make a pull request, if it's necessary_ :heart:  :blue_heart: :yellow_heart: :green_heart:

**Comment by apotonick** [comment]
Almost correct! :grin: It's documented here: http://trailblazerb.org/gems/cells/engine.html#view-paths Doesn't that work for you???

**Comment by Vorob-Astronaut** [comment]
```ruby
module Core::Cells
  class Application::Cell < Cell::Concept
    self_contained!
    class_name = name.split('::')[-2].downcase
    self.view_paths = ["#{Jobs::Cells::Engine.root}/app/concepts"] + ["#{Core::Cells::Engine.root}/app/concepts"]

    include ::Cell::Slim
  end
end
```
An error:
```
Template missing: view: `show.slim` prefixes: 
["/Users/vorob/Dropbox/ruby/devby_new/devby/components/jobs/cells/app/concepts/cores/asd/cell/views",
 "/Users/vorob/Dropbox/ruby/devby_new/devby/components/core/cells/app/concepts/cores/asd/cell/views",
 "/Users/vorob/Dropbox/ruby/devby_new/devby/components/jobs/cells/app/concepts/cores/application/cell/views", 
"/Users/vorob/Dropbox/ruby/devby_new/devby/components/core/cells/app/concepts/cores/application/cell/views"
```

The problem is: It pluralizes my engine name (_cores_, not just _core_), and doesn't add _cells_ subnamespace.

**Comment by apotonick** [comment]
The problem is here: https://github.com/apotonick/cells/blob/master/lib/cell/concept.rb#L13

Haha! :laughing: It removes the `Cell` from your namespace, leaving the single `s` which makes it look pluralized haha.

**Comment by apotonick** [comment]
Please, can you make the prefix regex catch the /::Cell$/ instead? Test goes here: https://github.com/apotonick/cells/blob/master/test/concept_test.rb#L41
