### ISSUE TITLE
ViewModel delegates don't work in tests.

### ISSUE THREAD

**Issue by tmullen** [apotonick/cells#307]
I'm running into an issue with my specs. It seems as though any initialized `Cell` object inside Rspec is not able to properly delegate `url_options`, `session`, etc.. I'm getting an "undefined method `url_options' for nil:NilClass" error for example. Run as part of the main rails app, this delegation works without any issues.

```ruby
require 'rails_helper'

RSpec.describe InvestmentProgressCell, type: :cell do

  let(:user) { create :user }
  let(:progress) { InvestmentProgress.new(user) }

  describe "#show" do
    subject { cell(:investment_progress, progress).call(:show) }
    it { is_expected.to have_selector('h1', text: 'Foo') }
    it { is_expected.to have_selector('p', text: 'Bar') }
  end

end
```

This commit seems to be the culprit: https://github.com/apotonick/cells/commit/31c88d1db8a7d49982a2b45aaf2b2627622ee439. Prior to that, I don't run into any problems. So, not sure if I need to include something in the specs or if this was an unintentional consequence of the change.

Any help would be much appreciated. Thanks!

cells: 4.0.2
rspec-cells: 0.3.3
cells-haml: 0.0.6

**Comment by apotonick** [comment]
This is documented here:

http://trailblazerb.org/gems/cells/testing.html#optional-controller

I will add that to the rspec-cells README, too. Sorry for the "clumsiness" of having to call `::controller` but Rails helpers need all kinds of dependencies everywhere so you need to specify them.

**Comment by tmullen** [comment]
That works for me. Thanks Nick!

**Comment by CJBrew** [comment]
Hi, 

I believe I've come up against this issue too, and I can't see how to fix it from this information. An example of what @tmullen did would be good!

My cell, as far as I know, doesn't need a "Optional Controller" -- if I had to pass that in, what should it be?

Here's an example project, I'd be grateful if you could take a look; I think most of the interesting stuff is in the readme on the front page:
https://bitbucket.org/CJBrew/cellstestbed

By the way @apotonick , the link above is wrong (changed?). It should be 
http://trailblazer.to/gems/cells/testing.html#optional-controller

**Comment by CJBrew** [comment]
Further, this info seems to have helped
https://github.com/apotonick/cells/wiki/From-Cells-3-to-Cells-4---Upgrading-Guide#migrating-from-cells-3-to-cells-4-with-rails-help

Gave me enough information to get this up and running:

``` ruby
    before do
      allow(controller).to receive(:current_user).and_return(nil)
    end

    it 'has the expected homepage_link' do
      content = cell(:nav, controller: controller).call
```
