### ISSUE TITLE
DRY way to handle subcomponents for rows

### ISSUE THREAD

**Issue by samstickland** [apotonick/cells#316]
Hi,

Is there a recommended way to create cells for a container with a subcell for each row. I currently end up implementing this using two cells.

app/cells/item_cell.rb:
````
class Items < Cell::ViewModel
  def show
    render
  end

  private
  
  def has_items?
    model.count > 0
  end

  def items
    model.proxy_association.scope.order('date DESC')
  end
end
````

app/cells/items/show.erb
````
<h1>Items</h1>
<% if has_items? %>
  <table>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Date</th>
    </tr>
    <%= cell(:item, collection: items) %>
  </table>
<% else %>
  <h2>No items found</h2>
<% end %>
````

app/cells/item_cell.erb
````
class Item < Cell::ViewModel
  property :id, :name

  def show
    render
  end

  private

  def date
     model.date.present? ? date.strftime('%b %Y') : ''
  end
end
````

app/cells/item/show.erb
````
<tr>
  <td><%= id %></td>
  <td><%= name %></td>
  <td><%= date %></td>
</tr>
````

Is there a DRYer way that I'm missing or is this the best way?

**Comment by samstickland** [comment]
I did consider creating a row view inside of items, but this means I end up calling the cell with different types of model which feels very icky, so I haven't gone done this route.

app/cells/item_cell.rb:
````
class Items < Cell::ViewModel
  property :id, :name

  def show
    render
  end

  private
  
  def has_items?
    model.count > 0
  end

  def items
    model.proxy_association.scope.order('date DESC')
  end

  def date
     model.date.present? ? date.strftime('%b %Y') : ''
  end
end
````

app/cells/items/show.erb
````
<h1>Items</h1>
<% if has_items? %>
  <table>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Date</th>
    </tr>
    <%= cell(:item, collection: items).(:row) %>
  </table>
<% else %>
  <h2>No items found</h2>
<% end %>
````

app/cells/item/row.erb
````
<tr>
  <td><%= id %></td>
  <td><%= name %></td>
  <td><%= date %></td>
</tr>
````

**Comment by apotonick** [comment]
I wonder what is not _DRY_ about your first example? I can't see redudance there.

It's best to have two cells for this kind of setup. We discuss a very similar case on pg. 79-81 in the Trailblazer book.

**Comment by samstickland** [comment]
I guess there isn't any real redundancy, but it felt a little split up, with app/cells/item/.. and app/cells/items/.. both needed to build the header and body of the table.

How would this look with concepts and not cells?

In the trailblazer book it uses:

````
class Thing::Cell < Cell::Concept
  class Grid < Cell::Concept 
````

but I can't find this structure in gemgem on github, instead it has:

````
class Thing::Cell < Cell::Concept
  class Row < self # inherit views thing/views/.
````

Which has left me a touch confused.

**Comment by apotonick** [comment]
There's a `Thing::Cell::Grid` here: https://github.com/apotonick/gemgem-trbrb/blob/chapter-10/app/concepts/thing/cell.rb#L21

And that grid simply renders the `Thing::Cell` (which represents one grid item). Does that help, or you still confused (:beer: helps)?
