### ISSUE TITLE
include Partial does not work

### ISSUE THREAD

**Issue by ryan2johnson9** [apotonick/cells#317]
Hello, 

I am using cells 4.02.

Unfortunately I still need to render a partial so that I can make use of Cocoon and its nice link_to_add_association method which requires a partial.

I read the guide here
Rendering Global Partials

and did this:

    class LocationVariableCell < Cell::ViewModel
      include Formtastic::Helpers::FormHelper
      include ActionView::RecordIdentifier
      include ActionView::Helpers::FormOptionsHelper # for formtastic select calls select helper
      include ActionView::Helpers::TranslationHelper # for t translation method
      include Cocoon::ViewHelpers
      include Authorization::AuthorizationHelper # for permitted_to?
      include AbstractController::Helpers # for helper_method needed by Devise
      include Devise::Controllers::Helpers # for current_user
      include TranslationsHelper # for tlabel
      include ButtonLinkHelper # for icon_link used by tlink_to_icon
      include LocationHelper # for display_collection_like_tree(@perm_locations)
      include Partial

but I get error

uninitialized constant LocationVariableCell::Partial

here is the first part of the backtrace

    app/cells/location_variable_cell.rb:14:in `__script__'
    app/cells/location_variable_cell.rb:1:in `__script__'
    activesupport (4.1.6) lib/active_support/inflector/methods.rb:238:in `constantize'
    activesupport (4.1.6) lib/active_support/inflector/methods.rb:236:in `constantize'
    activesupport (4.1.6) lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
    cells (4.0.2) lib/cell/view_model.rb:78:in `class_from_cell_name'
    cells (4.0.2) lib/cell/view_model.rb:39:in `cell'
    cells (4.0.2) lib/cell/rails.rb:6:in `cell'
    cells (4.0.2) lib/cell/rails.rb:20:in `cell'
    app/views/location_variables/edit.haml:12:in `_app_views_location_variables_edit_haml__1547421109874181847_9140608'
    actionview (4.1.6) lib/action_view/template.rb:145:in `render'
    activesupport (4.1.6) lib/active_support/notifications.rb:161:in `instrument'
    actionview (4.1.6) lib/action_view/template.rb:339:in `instrument'
    actionview (4.1.6) lib/action_view/template.rb:143:in `render'
    actionview (4.1.6) lib/action_view/renderer/template_renderer.rb:55:in `render_template'
    actionview (4.1.6) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
    activesupport (4.1.6) lib/active_support/notifications.rb:159:in `instrument'
    activesupport (4.1.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    activesupport (4.1.6) lib/active_support/notifications.rb:159:in `instrument'

**Comment by apotonick** [comment]
Wow, that's a lot of helpers you need for a little cell...!

You need to `require "cell/partial"`.

**Comment by ryan2johnson9** [comment]
Yeh I know!

Thanks, now I can require 'cells/partial'. However it does not seem to do anything. I get the same error as before I tried to `include Partial`. The render call from within the (nested) cell looks like this:

`  = render partial: 'translation_nested_fields'`

gives this very strange error:

(when rendered from within debugger):

    Template missing: view: `__metaclass_init__.haml` prefixes: ["app/cells/location_variable"] (Cell::TemplateMissingError)
                Cell::ViewModel::TemplateFor(LocationVariableCell)#find_template at /home/ryan/.rvm/gems/rbx-2.5.7@rails4.1_registration/gems/cells-4.0.2/lib/cell
                                                                                    /view_model.rb:188
               Cell::ViewModel::Rendering(LocationVariableCell)#render_to_string at /home/ryan/.rvm/gems/rbx-2.5.7@rails4.1_registration/gems/cells-4.0.2/lib/cell
                                                                                    /view_model.rb:117
                         Cell::ViewModel::Rendering(LocationVariableCell)#render at /home/ryan/.rvm/gems/rbx-2.5.7@rails4.1_registration/gems/cells-4.0.2/lib/cell
                                                                                    /view_model.rb:112

when rendered normally in HAML

    ActionView::Template::Error (Template missing: view: `__tilt_22303564.haml` prefixes: ["app/cells/location_variable"]):
    app/cells/location_variable/edit_letter_translations.haml:4:in `__tilt_22303564'
    app/cells/location_variable/edit_letter_translations.haml:-8:in `__tilt_22303564'
    app/cells/location_variable/edit_letter_translations.haml:-10:in `__tilt_22303564'
    app/cells/location_variable_cell.rb:116:in `edit_letter_translations'
    app/cells/location_variable/edit.haml:28:in `__tilt_22303564'
    app/cells/location_variable/edit.haml:18:in `__tilt_22303564'
    app/cells/location_variable/edit.haml:-8:in `__tilt_22303564'
    app/cells/location_variable/edit.haml:-10:in `__tilt_22303564'
    app/cells/location_variable_cell.rb:20:in `edit'
    app/views/location_variables/edit.haml:12:in `_app_views_location_variables_edit_haml__1547421109874181847_9140608'
    app/controllers/location_location_variables_controller.rb:113:in `edit'
    app/controllers/location_location_variables_controller.rb:112:in `edit'

The partial is defined at "app/cells/location_variable/_translation_nested_form.haml

**Comment by apotonick** [comment]
Ha! The `render partial:` still doesn't know where your partials are. http://trailblazerb.org/gems/cells/render.html#partials

Why are you using a global partial in the first place, I wonder?

**Comment by apotonick** [comment]
I re-checked and this is also documented directly in the README, in the undocumented section, haha: https://github.com/apotonick/cells#rendering-global-partials Protip: `Ctrl+F` on GH README page can save you time.

**Comment by apotonick** [comment]
(and me). :beers:

**Comment by ryan2johnson9** [comment]
Yes I read that section, found using my nifty Ctrl-F on my browser. :)

I don't want to use a global partial, I want to simply use a partial (required by cocoon) and the only info on the README is for Global Partials. I just wanted to put it in with the folder for all my cells views.

I've tried a number of things now, including and not including the .haml extension. Including and not including the `_` at the front of the partial. Ensuring the name of my partial is correct. Taking the partial out of the folder of my cells views and putting it in my normal view paths and trying to access it like in the Readme. Removing the `require 'partial'` line.

appending to the view paths using

`self.view_paths << 'app/views/location_variables'`

this seems to have a bug
see how my appended view path has had the name of the cell added to it: `"app/views/location_variables/location_variable"`

`ActionView::Template::Error (Template missing: view: `__tilt_1144364.haml` prefixes: ["app/cells/location_variable", "app/views/location_variables/location_variable"]):`

But even if I account for this seeming bug (by appending 'app/views/') and putting my partial in a folder called 'location_variable'

I always get this error about not being able to find '__tilt_.........'

I'm stumped..

**Comment by ryan2johnson9** [comment]
__tilt_1471860.haml, always has a different number on the end, before the  haml extension

**Comment by apotonick** [comment]
@ryan2johnson9 Can you join the https://gitter.im/trailblazer/chat channel for a minute so we can resolve this?

**Comment by ryan2johnson9** [comment]
Thanks for the chat @apotonick .
 
It seems that the Readme is no longer true for cells 4.0.2. Although I did not need to render a Global partial in the end, I still experimented with this on my way and found a) `include Partial` raises an error and should be require 'cells/partial', but then from there I could not render a global partial anyway.

The solution for me to render a partial defined in my cells/location_variable folder was as you suggested ` = render view: '_translation_nested_form', locals:{ f: trans_form, disable: false } `

so shall I investigate and be sure that the README rendering partials is incorrect, and then add a pull request for the readme?

Also is it an error with the view_paths as suggested above? i.e. no matter what view path is put in, the name of the cell is always added at the end of the path. Or is this intended?

And do you think it would be helpful for me to add something to the readme about rendering partials in general, in the "please do not read section"?

One more thing, The biggest issue I faced was making use of Cocoon's link_to_add_association method which asks for the name of a partial. With @apotonick's encouragement I managed to do a monkey patch for Cocoon so that it uses the correct render call. Here is my monkey patch for anyone else in this situation:

from within the cell, when you call link_to_add_association, pass in a render option `cells_compatible:true` like this:
  
    link_to_add_association "add", @form, :association_name,
                              :partial => "_partial_name", render_options:{cells_compatible:true}

(note the leading underscore required in the partial_name)

in some model, or however you like to do monkey patches, (I use a class_extensions.rb file in my models directory) add this code:

    require 'cocoon/view_helpers'
    # overwrite the cocoon method which renders the partial for adding associations in the link_to_add_association helper method
    module Cocoon
      module ViewHelpers
        def render_association(association, f, new_object, form_name, render_options={}, custom_partial=nil)
          partial = get_partial_path(custom_partial, association)
          locals =  render_options.delete(:locals) || {}
          cells_compatible = render_options.delete(:cells_compatible)
          method_name = f.respond_to?(:semantic_fields_for) ? :semantic_fields_for : (f.respond_to?(:simple_fields_for) ? :simple_fields_for : :fields_for)
          f.send(method_name, association, new_object, {:child_index => "new_#{association}"}.merge(render_options)) do |builder|
            partial_options = {form_name.to_sym => builder, :dynamic => true}.merge(locals)
            if cells_compatible
              render view: partial, locals: partial_options
            else
              render(partial, partial_options)
            end
          end
        end
      end
    end

This simply overwrites the same method in Coccon which looks like this

    def render_association(association, f, new_object, form_name, render_options={}, custom_partial=nil)
      partial = get_partial_path(custom_partial, association)
      locals =  render_options.delete(:locals) || {}
      method_name = f.respond_to?(:semantic_fields_for) ? :semantic_fields_for : (f.respond_to?(:simple_fields_for) ? :simple_fields_for : :fields_for)
      f.send(method_name, association, new_object, {:child_index => "new_#{association}"}.merge(render_options)) do |builder|
        partial_options = {form_name.to_sym => builder, :dynamic => true}.merge(locals)
        render(partial, partial_options)
      end
    end

I will raise an issue with Cocoon now to see if they think it is worth me making a pull request.

**Comment by ryan2johnson9** [comment]
https://github.com/nathanvda/cocoon/issues/315

**Comment by apotonick** [comment]
The `ViewModel::view_paths` directive is meant as the path to where all the cells reside (similar to `AC::view_paths`). The actual paths to the cell's views is available via `ViewModel#prefixes`, you need to override that to point to another directory (but do _you_ really need this?).

`render partial: ..`'s documentation is reflecting the actual behavior, see here: https://github.com/apotonick/cells/blob/master/test/partial_test.rb#L12 The difference is that your partial is _not_ in a global directory.

I am probably gonna move the partial code to a separate gem soon (`cells-partial` or something), just to further discriminate this. I find it wrong to render partials from other stacks in a cell and want to ban this explicitly, otherwise people will keep hacking stuff instead of fixing the actual gem. Also, I then don't have to support this madness anymore. :wink: 

The cleanest solution would be to "fix" `#render` in your cell, so when subsequent calls to `render` from cocoon are detected, change their API to ours. And the cleanestest would be cocoon using cells in general, but... :stuck_out_tongue_winking_eye:

**Comment by nathanvda** [comment]
How can cocoon see if we are being rendered in a cell? The suggested change is to give a parameter to `link_to_add_association` and change the render call in that case, which seems ok to me. I definitely love to support cells, but I also want to stay backward compatible :wink: :stuck_out_tongue_winking_eye:

**Comment by apotonick** [comment]
@nathanvda You can't see that, right, that's why I suggested @ryan2johnson9 to patch _his_ `#render` and detect when it's a call from cocoon and when not.

Ideally, Cocoon would use Cells to render its elements in general. I am about to write a new form builder based on Cells, maybe that can be source of inspiration? :wine_glass:

**Comment by ryan2johnson9** [comment]
Ahh ok, so Cocoon's render call is hitting Cells render method, rather than the global render helper. So If I adjust my Cells render method detect when the render call is meant for the global render, and massage the parameters there before handing them onto super that would be cleaner than introducing a conditional statement into @nathanvda 's Cocoon's internals. It would mean my overwriting render method in my cell would have to be able to accept both combinations of paramaters, i.e

from Cells::ViewModel the render method params = `def render(options={})`
from ActionView::Helpers::RenderingHelper `def render(options = {}, locals = {}, &block)`

I'll give it a whirl, Ta

**Comment by nathanvda** [comment]
Ok, now you got me confused :confused: :smile: cocoon just renders a partial to be inserted later inside a form, and cocoon does not know how this form is rendered. So not entirely sure what you mean precisely (when you say: use cells to render its elements?).

But when writing a new form builder, based on cells, yes then it would seem more obvious, and very interesting. Completly OT: I still need to check out Reform+cocoon together :smile:

**Comment by nathanvda** [comment]
Ha! Ok, @ryan2johnson9 makes sense :smile:

**Comment by ryan2johnson9** [comment]
:)

**Comment by ryan2johnson9** [comment]
Ok, here is my 'cleaner' solution as suggested by @apotonick(though not condoned :) ) . Brace yourselves, it may be cringeworthy, but for me it works pretty well so far and has helped me to understand better the issue that @apotonick has been trying to teach me.. i.e. there are problems when a gem makes use of a global rails helper such as `render`. I wonder what the alternative is then for such gems, should they explicitly include the helpers they need rather than rely on them being in the global set of helpers? I think I need to read that Trailblazer book.

Anyway here is the code I added to my Cell, I'll probably extract it into a module and include it when I need to use it in other cells:

    # Need to overwrite the cells render so that we can use Cocoon in the edit_letter_translations view
    # Cocoon assumes it is using ActionView::Helpers::RenderingHelper render method which accepts these parameters: def render(options = {}, locals = {}, &block)
    # but when rendered in the context of a cell, it hits the Cells::ViewModel render method which accepts different params = def render(options={})
    # so accept all params and massage these before sending them onto the Cells::ViewModel render with 'super'
    def render(options = nil, locals = nil, &block)
      #CASE 1 Cell calls render without arguments
      if options.nil?
        super(state_for_implicit_render(caller))
  
      #Case 2 Cell calls render with either the name of a view or a single optios Hash as its paramater
      elsif options.present? && locals.nil?
        super options
  
      #Case 3 render is called by Cocoon, intended for ActionView::Helpers::RenderingHelper so massage params such that Cells render can handle it
      elsif options.is_a?(String) && locals.is_a?(Hash)
        if block_given?
          raise "sorry don't know how to handle block in this custom override - ryan - see app/cells/location_variable_cell.rb:32"
        end
        super({view: options, locals: locals})
      else
        raise "Woops, this overriding render method written so that we could make use of Cocoon in Cells did not handle a render call properly, please see app/cells/location_variable_cell.rb"
      end
    end
 
This covers all the cases I need to use render for, but I won't be surprised if we hit the "Woops" error one day.

**Comment by apotonick** [comment]
Thanks for posting it.

You don't have to differentiate between case 1. and 2., the cell will do that for you.

**Comment by ryan2johnson9** [comment]
I had to do that because 'caller' in the context of Cells::ViewModel render is no longer my cells method, e.g. edit, when render hits my overwriting method first.

**Comment by apotonick** [comment]
ARgh, you're right. I personally hate this little piece of magic in my code, especially that it only saves 5 characters:

```ruby
render
```
vs.

```ruby
render :show
```

**Comment by ryan2johnson9** [comment]
Yeah, nice one! Rails developers start to expect magic I guess.

**Comment by apotonick** [comment]
But my gems are not Rails, which is why I might remove this in the near future.

**Comment by ryan2johnson9** [comment]
:+1:

**Comment by Startouf** [comment]
Hello there, 
Sorry to come here after the battle, I also wish to use Cocoon with cells, but when using @ryan2johnson9's last fix, I run into one more issue. It seems that the partial name is not resolved correctly, and instead the library keeps looking for a `render_state.erb` file instead of the right file.

`Template missing: view: `render_state.erb` prefixes: ["app/cells/company", "app/cells/default"]`

(Instead of "app/cells/company/dashboard.erb")

I am defining the new `render` override in a `default_cell.rb` which is then inherited by other cells.

I am rendering a custom action `dashboard` of my CompanyCell

```ruby
# app/cells/default_cell.rb
require "cell/partial"

class DefaultCell < Cell::ViewModel
  # include ActionView::Helpers
  include SimpleEnum::ViewHelpers
  include ActionView::Helpers::TranslationHelper
  include ActionView::Helpers::FormHelper
  include ActionView::Helpers::FormOptionsHelper
  include Cocoon::ViewHelpers
  include ::TranslationHelper
  include BootstrapHelper
  include Partial

  def render(options = nil, locals = nil, &block)
    # @ryan2johnson9's last fix
  end

# app/cells/company_cell.rb
class CompanyCell < DefaultCell
  def dashboard
    render
  end
```
The error happens on the call `super(state_for_implicit_render(caller))`

Relevant stack trace

```
C:/dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cells-4.0.4/lib/cell/view_model.rb:182:in `find_template'
C:/dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cells-4.0.4/lib/cell/view_model.rb:112:in `render_to_string'
C:/dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cells-4.0.4/lib/cell/view_model.rb:107:in `render'
app/cells/default_cell.rb:23:in `render'
app/cells/company_cell.rb:3:in `dashboard'
```

I am using cells (4.0.4), RoR 5.0.0beta3

Otherwise, @apotonick you mentionned working on a proper Cocoon implementation for cells, any update on that ?

**Comment by apotonick** [comment]
Sorry, I have no idea about what @ryan2johnson9 does in your code, but overriding `#render` is problematic, you should call it with the view name, instead.

```ruby
render :view_you_actually_wanna_render
```

Not working on any Cocoon stuff, I don't even know what it is?

**Comment by Startouf** [comment]
Oh sorry, read too fast and I was inaccurate. I was reffering to this, but indeed nothing especially concerning Cocoon

> Ideally, Cocoon would use Cells to render its elements in general. I am about to write a new form builder based on Cells, maybe that can be source of inspiration?

However I see there has been a new comment concerning this in the [associated issue of the Cocoon issue tracker](https://github.com/nathanvda/cocoon/issues/315)  . Apparently someone is working on appropriate Cocoon helpers to be included in Cells
I will look at this commit from @asaletnik ["add separate helpers for cells, with proper render method call"](https://github.com/asaletnik/cocoon/commit/7c864f85c892fe21feeead09933f751e6773bdf6)

**Comment by apotonick** [comment]
I *like* that a lot!!! :stuck_out_tongue_winking_eye:

**Comment by ryan2johnson9** [comment]
@Startouf sorry I did not see your post til now. I came across the same error re `render_state.erb` when using the monkey patch I added here. I solved it by never using simply `render` but always specifying the name of the template. e.g. `render "show"`, (i.e. the `if options.nil?` block in my monkey patch is now broken so I avoid it). I have not tried the Cocoon::Cells Helper yet but will do soon as I'm keen to remove the monkey patch from my code. How did you go with the Helper, did it work for you?

**Comment by phillipoertel** [comment]
@apotonick now that there's cells_rails, wouldn't it make sense to add this (and other stuff expected in Rails context) by default there. It took me a while to figure out what I needed to do when migrating existing partials into cells; this work could be saved by future developers if they could just inherit from Cells::Rails.
