### ISSUE TITLE
Relative I18N translation paths do not work in a cell (need @virtual_path)

### ISSUE THREAD

**Issue by johnlane** [apotonick/cells#319]
Using the Rails I18N translation helper `t` to translate a relative keyword (e.g. `t(.foo)` in a Cell produces an error: 

    Cannot use t(".foo") shortcut because path is not available

Fixing this requires setting `@virtual_path = "path.to.view"`.

To reproduce:
* in a cell: `include ActionView::Helpers::TranslationHelper`
* in a view: `t('.foo')`

Work-arounds are either
* use absolute translation paths, or
* set `@vitual_path` either in the cell or in its view.

This also provokes thinking about what the `@virtual_path` should be set to. Given a cell `app/concepts/a/b/cell.rb` with views `app/concepts/a/b/views/x` and `app/concepts/a/b/views/y`. Options include
* concept root : `a`
* cell root: `a.b`
* view root: `a.b.x` and `a.b.y`

I am not sure which is best. I'm currently using the first option but I think the second one might be better.

The above is with Cells 4.0.2.

I just checked on some old code with Cells 3.10.1 and that did set the path to the cell name (i.e for `app/cells/x`, it set it to `x`).

**Comment by apotonick** [comment]
Cool, thanks so much for your investigations @johnlane, very helpful! :beers: 

Doesn't I18N traverse the "path" by iteratively removing the last element? In that case, the full namespace path would probably be more precise.

If `a.b` can't be resolved, `a` is used (as far as I remember that from validations in Reform).

@johnlane Could you write a new test (`test/i18n_test.rb`) so we can refine things in the code?

**Comment by johnlane** [comment]
I'll have a look at writing a test.

Re the upward traversal... you would expect so wouldn't you?

From what I can see the `t` helper looks at `@vrtual_path` as given. If the lookup fails then that's it.

Here's a snippt from `actionview-4.2.4/lib/action_view/helpers/translation_helper.rb`:
```ruby
        def scope_key_by_partial(key)
          if key.to_s.first == "."
            if @virtual_path
              @virtual_path.gsub(%r{/_?}, ".") + key.to_s
            else
              raise "Cannot use t(#{key.inspect}) shortcut because path is not available"
            end   
          else
            key 
          end 
        end
```

**Comment by johnlane** [comment]
Sent PR https://github.com/apotonick/cells/pull/320 with tests

**Comment by apotonick** [comment]
Should we simply add the cell path (e.g. `admin/comment`) and maybe provide `ViewModel::translate_path "admin"` if you need to fine tune? That should work just fine?!

**Comment by johnlane** [comment]
Yes I think the cell path by default and being able to customise it makes the most sense.

**Comment by phillipoertel** [comment]
Hi @apotonick, with cells 4.0.4 I still had to `require cell/translation` in order for everything to work.

**Comment by apotonick** [comment]
Hi @phillipoertel - isn't that how it's supposed to be? We don't do autoloading in most TRB gems anymore because it always breaks, this is why people have to manually require files. :beers:

**Comment by phillipoertel** [comment]
Fair enough! Some modules (like Escaped) don't require an explicit require though, so I'd either make it consistent  or document in each case if/what needs to be included.

Btw., how stable is the TRB codebase & API right now? I took a look a few months ago, but it seemed to me there were several ways to do things (and several different documentations), while none of them was easy to get to work :-) I'd love to take another look when the time is right.

**Comment by apotonick** [comment]
Cool, thanks @phillipoertel ! TRB is in more than 200 production apps already and very stable! It's very easy now with the `trailblazer-rails` gem. :beers:

**Comment by phillipoertel** [comment]
Alright, I'll have a look when I find the time. Kudos to your heroic efforts with this, mate!

**Comment by phillipoertel** [comment]
Btw. one of the projects I'm in uses https://github.com/cypriss/mutations and we're looking into https://github.com/orgsync/active_interaction. They solve the encapsulation-of-application-specific-business-logic problem, as well.

**Comment by apotonick** [comment]
The idea is to use those gems from within the operation - not excluding each other. I also love https://github.com/icelab/call_sheet
