### ISSUE TITLE
Documentation is difficult to get up and running with

### ISSUE THREAD

**Issue by adsteel** [apotonick/cells#345]
Based on the current readme, it took me a lot of guesswork and calls to `binding.pry` to make a very basic Cells implementation in my current app. As is, I may hit a timeout on the concept before I have a chance to really build a good example to bring to my colleagues. If I figure it all out, I may have capacity to improve the readme myself, but I wanted to log this issue in case anyone else has ideas.

**Comment by apotonick** [comment]
Are you confusing `Cell::ViewModel` and `Cell::Concept`? The documentation clearly distinguishes between them. Note that all documentation is getting moved here http://trailblazer.to/gems/cells/ and to the books, but you're more than welcome to help improving it.

**Comment by apotonick** [comment]
And join the Gitter channel if you need help. I will add _Getting Started_ tutorials for every Trailblazer gem in a few weeks but in the meantime, come chat with us.
