### ISSUE TITLE
autoloading issues

### ISSUE THREAD

**Issue by sdesbure** [apotonick/cells#350]
Hello, not sure if it's here but I give a try:
I use cells (and trailblazer in general).
In order to refactor, I've created a module reused in some cells:
`TypeIcon` put in `app/cells/type_icon.rb`:

```ruby
module Cell::TypeIcon
  private
    
  def type_icon
  end
end
```

I then include it in my concepts:
for example in `Application::Cell`put in `app/concepts/application/cell.rb`:

```ruby
class Application::Cell < Cell::Concept
  include AbstractController::Helpers
  include Monban::ControllerHelpers
  include Cell::TypeIcon

   def show
     render
   end
end
```

but when I start rails, I have the following error:

```
Users/sylvain/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:495:in `load_missing_constant': Unable to autoload constant TypeIcon, expected /Users/sylvain/Sources/EasyConnectPortal/app/cells/type_icon.rb to define it (LoadError)
	from /Users/sylvain/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/sylvain/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:526:in `load_missing_constant'
	from /Users/sylvain/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/sylvain/Sources/EasyConnectPortal/app/concepts/application/cell.rb:4:in `<class:Cell>'
	from /Users/sylvain/Sources/EasyConnectPortal/app/concepts/application/cell.rb:1:in `<top (required)>'
```

If I comment the line, start, uncomment, refresh, it works after another refresh (the first one whine about the missing constant but not the second one). 
Any hints to make it work?

thanks!

**Comment by Tab10id** [comment]
app/cells/type_icon.rb - module TypeIcon
app/cells/cell/type_icon.rb - module Cell::TypeIcon
Directory names should correspond to namespaces

**Comment by apotonick** [comment]
Exactly! :smile: It's a pure Rails autoloading issue! Thanks @Tab10id! @sdesbure - jump on the https://gitter.im/trailblazer/chat channel if you need support.

**Comment by sdesbure** [comment]
Hello,
thanks for the answer! I tried with `app/cell` but wasn't working either so I thought it was a different story!
thanks guys

**Comment by apotonick** [comment]
No no, `app/XXX/toplevel/bla.rb` where the file `bla.rb` is `Toplevel::Bla`. The directory between `app` and `toplevel` could be `dfjzkcxjalsdfjalskdfj1` and it would still work.
