### ISSUE TITLE
Critical bug: ViewModel.property(*names) vs Escaped::Property#property(name, *args) 

### ISSUE THREAD

**Issue by xzo** [apotonick/cells#359]
include Escaped
    property :property1, :property2

Escaped does not escape property2.

**Comment by apotonick** [comment]
Do you want to PR? :heart_eyes:

**Comment by xzo** [comment]
What about method, that escape methods explicitly?
`escaped :property1, :property3`

**Comment by apotonick** [comment]
Is that necessary? I don't think so... the less API the better. We should fix the existing `Escaped` module. Are you keen to do so?
