### ISSUE TITLE
Hamlit missing autoloading/including

### ISSUE THREAD

**Issue by Kledal** [apotonick/cells#372]
When I try to create a `Cell::Concept` and using the cells-hamlit gem as my template engine. 

I this error:
```ruby 
undefined method `template_options_for'
```

It works if I manually insert this into my Cell: 
```ruby
include Cells::Hamit
```

So the reason I'm getting this error is because when using `cells-hamlit`, the gem defines a module called `Hamlit` and this module is not autoloaded in the `railtie.rb` file. It only preloads `Cells::Haml` 

I don't know if this is a bug in this gem or if it is a bug in the cells-hamlit gem. I will link a PR with the hamlit added to railtie.

**Comment by timoschilling** [comment]
would be closed by #342
