### ISSUE TITLE
"SystemStackError: stack level too deep" when defining delegator method with hash model

### ISSUE THREAD

**Issue by mstanielewicz** [apotonick/cells#375]
My cell model is a hash with following structure:

> {:toggl_project_id=>111111111,
 :toggl_hours_data=>
  [{:date=>Mon, 01 Feb 2016, :billable=>7.56, :non_billable=>7.15},
   {:date=>Tue, 02 Feb 2016, :billable=>7.52, :non_billable=>0.0},
   {:date=>Wed, 03 Feb 2016, :billable=>8.22, :non_billable=>2.53},
   {:date=>Thu, 04 Feb 2016, :billable=>6.74, :non_billable=>1.79},
   {:date=>Fri, 05 Feb 2016, :billable=>5.55, :non_billable=>5.66},
   {:date=>Sat, 06 Feb 2016, :billable=>0.0, :non_billable=>0.0},
   {:date=>Sun, 07 Feb 2016, :billable=>0.0, :non_billable=>0.0},
   {:date=>"total", :billable=>35.58, :non_billable=>17.13}],
 :from_date=>Mon, 01 Feb 2016,
 :to_date=>Sun, 07 Feb 2016}

I defined a delegator methods, since property method is used for object model. So I have methods like: 

>     def toggl_hours_data
      model[:toggl_hours_data]
    end

When I try to use method:

>     def non_billable
      toggl_hours_data.map { |day| day.slice(:date, :non_billable) }
    end

I ended up with `SystemStackError: stack level too deep`
The strange thing is that when I put a debugger and pasted the method code in the console it worked.

**Comment by apotonick** [comment]
Is it possible to catch the first 10 lines of that exception?

**Comment by mstanielewicz** [comment]
The strange thing is that I cannot recreate it now, but it is not the first time I had this problem. It happened to me a few times when working with hash models, when used delegator methods like this and called them in some places.
I'm pretty sure there wasn't any call stack with that error. It was just

>  SystemStackError: stack level too deep

which showed the line that was using the delegator method. And that's it. If I spot this problem again, I'll capture the exact message.
The issue is strange because when I use the exacly same thing next time, with no changes in the code it worked ok.
