### ISSUE TITLE
Testing cells with Rails 5

### ISSUE THREAD

**Issue by mrship** [apotonick/cells#376]
I'm working with Cells 4.0.4, Rails 5.0.0.beta2 and RSpec 3.5 and having issues with testing. Specifically, with this spec:

```
include Cell::Testing
RSpec.describe PropertyCell do
  controller PropertiesController

  describe '#show' do
    it 'renders a form' do
      expect(cell(:property, property).()).to include("form")
    end
  end
end
```

There's an error thrown when the cell method is called:

```
     ArgumentError:
       wrong number of arguments (given 0, expected 2)
```

This appears to be from:

```
      controller_class.new.tap do |ctl|
        ctl.request = ::ActionController::TestRequest.new
        ctl.instance_variable_set :@routes, ::Rails.application.routes.url_helpers
      end
```

in `cells-4.0.4/lib/cell/testing.rb:49` because under Rails 5, you can't instantiate a `TestRequest` without an env and a session. The fix is to use `::ActionController::TestRequest.create` instead, but that won't work under Rails 4 because it's a new class method under Rails 5.

I can work around it by patching cells to use the `.create` call, but I'm not sure how best to fix that for Rails 5 and maintain compatibility with earlier versions of Rails. Perhaps you have more insight into a way to have the testing work for both?

Also, I have to add `include Cell::Testing` to get the controller action to be defined as this isn't automatically added (as I expect it is under Rails 4).

Thanks for a great library in Cells, it's working well for me even with these testing issues.

**Comment by apotonick** [comment]
This is fixed in cells-rails 0.0.6. Thanks @dan-palmer and @mrship for helping!!! :beers:
