### ISSUE TITLE
customized views per request à la `prepend_view_path`

### ISSUE THREAD

**Issue by apneadiving** [apotonick/cells#385]
Hi and thanks for the gem (and its presentation in belgium :) )

I was wondering how you'd mimic a mechanism like `prepend_view_path`.
I'm well aware of `self.view_paths` but this is not what I'm looking for:
- `prepend_view_path` has the benefit of being per request so I can customize views based on user
- if I touch `view_paths`, it will persist across requests

I was considering to store relevant data in the current thread to be able to access it globally (yes I know), instead of passing data across all cells.

Do you have any recommendations?

Thanks,

Ben

**Comment by apneadiving** [comment]
Maybe a better solution would be to override[ this method](https://github.com/apotonick/cells/blob/62d919050acc84117b4da5ba0146af2fdf24db4d/lib/cell/partial.rb#L13).
Something like:
```ruby
  def process_options!(options)
    super
    return unless partial = options[:partial]

    parts     = partial.split("/")
    view      = parts.pop
    view      = "_#{view}"
    view     += ".#{options[:formats].first}" if options[:formats]
    prefixes  = view_paths.collect { |path| ([path] + parts).join("/") }

    options.merge!(view: view, prefixes: prefixes)
  end

  def view_paths
    custom_view_paths || default_view_paths
  end

  def custom_view_paths
    nil
  end

  def default_view_paths
    self.class.view_paths
  end
```

This way `custom_view_paths` could be changed by people easily.

**Comment by apneadiving** [comment]
Seems the solution [lies here ](https://github.com/apotonick/cells/blob/master/lib/cell/prefixes.rb#L12) with a hook to change prefixes if need be.
I'll try and close in case of success

**Comment by apneadiving** [comment]
I confirm this works

```ruby
class AbstractCell < Cell::ViewModel

  def self.prefixes
    custom_list = super
    if custom_path.present?
      custom_list = custom_list.map {|path| path.gsub('app/cells', "app/cells/#{custom_path}")} + custom_list
    end
    custom_list
  end

  def self.custom_path
    Thread.current[:custom_path]
  end
end
```

I would be curious to hear your thoughts about it

**Comment by apotonick** [comment]
Hey Ben!!! Good to see you here!

That's correct, the `#prefixes` method is designed to do that. We played with other ideas but this is pretty straight-forward and simple. 

Let me know if you need more help!

**Comment by apneadiving** [comment]
:)

Do you feel relying on the Thread is ok?

**Comment by apotonick** [comment]
Hell no, that's a global variable, but that's your problem haha! You could also inject the custom path as an option and then use the `:prefixes` option when rendering: https://github.com/apotonick/cells/blob/master/lib/cell/view_model.rb#L167

Does that help?

**Comment by apneadiving** [comment]
It does thanks.

Having an additional param doesnt please me that much though: I'd have 20 cells to update.

I like the idea behind Rails' prepend_view_path so I'll stick with this :)

Thanks for your answers :)

**Comment by apotonick** [comment]
You should definitely go the functional-explicit way and pass those options into the cell, you could override the `cell` helper for that and do it there. https://github.com/apotonick/cells/blob/master/lib/cell/rails.rb#L5

What you do right now is "less clumsy" but depends on global state, very hard to test, very hard to maintain, keep the explicit "pass customization as arguments" in mind. :stuck_out_tongue_winking_eye:
