### ISSUE TITLE
undefined local variable or method `view_renderer'

### ISSUE THREAD

**Issue by Startouf** [apotonick/cells#386]
I am trying to move some code from an existing Rails app to some cells. I ran into this error, can't find any hit on google.

Config

- Rails 5 beta3
- Cells 4.0.4, Cells-erb 0.0.7

Classes

```ruby
# cells/employee_cell.rb
class EmployeeCell < ProfessionalCell
end

# cells/professional_cell.rb
class ProfessionalCell < DefaultCell
  def show
    render
  end
end

# cells/default_cell.rb
class DefaultCell < Cell::ViewModel
  include Escaped
  include ActionView::Helpers # Temporary, until I can figure out which specific helpers to include exactly
end
```

In my view
`<%= cell(:employee, @employee).(:show) %>`

Error

> ActionView::Template::Error (undefined local variable or method `view_renderer' for #<EmployeeCell:0x0000000ac8da98>):

What did I do wrong ?

**Comment by apotonick** [comment]
Please don't include all helpers if you don't have to. I could probably point you to where's the problem if I could see the first 10 lines for the stack trace. It's one of the Rails helpers in you `show` view, definitely.

**Comment by Startouf** [comment]
Ah yes, because I was using a variety of helpers, I thought I could just bruteforce-include all helpers now and then take some time later to only include the ones I needed. But yes, it seems one Helper is overriding the render method defined for your library.

```ruby
C:/dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/actionview-5.0.0.beta3/lib/action_view/helpers/rendering_helper.rb:32:in `render'
> app/cells/professional_cell.rb:11:in `show'
```

So I guess there's no help including them one by one until I get rid of all errors ? Or I *could* include [all those rails helpers](http://api.rubyonrails.org/classes/ActionView/Helpers.html) except the `rendering_helper` one ?

**Comment by apotonick** [comment]
Only include the ones you need!
