### ISSUE TITLE
Concepts (and probably Cells) should be able to use the `concept` helper

### ISSUE THREAD

**Issue by pnomolos** [apotonick/cells#387]
Right now I've added

```ruby
module Cell
  class ViewModel
    def concept(name, model=nil, options={}, &block)
      ::Cell::Concept.cell(name, model, options.merge(controller: parent_controller), &block)
    end
  end
end
```

to a rails initializer so that I can use `concept` inside a concept that's being rendered.

**Comment by apotonick** [comment]
I've changed that in Cells 4.1 (and upcoming 5.0). The main point is you shouldn't mix naming styles, and in that sense, `Concept::cell` will alias to `concept` which will *now* resolve a concept cell, and not an old-style cell anymore.

Thanks for reporting!

**Comment by pnomolos** [comment]
@apotonick Cool, thanks!
