### ISSUE TITLE
Render custom cell using js or sass format

### ISSUE THREAD

**Issue by jhblacklock** [apotonick/cells#390]
I'm updating our cells versions to 4.0.4.  Previously we were able to make customized cells with js and sass assets within the following cell folder structure.

```
├── form
│   ├── stylesheet.sass
│   ├── javascript.js
│   ├── show.haml
│   ├── edit.haml
├── form_cell.rb`
```

form_cell.rb had render methods using non-erb/haml rendering.

```
def javascript(_opts)
    render formats: [:js]
 rescue
   ::Rails.logger.debug 'No javascript for cell'
   ''
 end

def stylesheet(_opts)
   render formats: [:sass]
rescue
  ::Rails.logger.debug 'No stylesheet for cell' 
  ''
end
```

We combine all of the cells js and sass through Sprockets and build custom assets delivered through the pipeline per view.

We can render our haml files using cells-haml but the js and sass mime-types are no longer recognized.  

We've used:

`render view: 'stylesheet.sass', format: :sass`

But cells still tries to render as haml.

**Comment by apotonick** [comment]
You might have to override https://github.com/trailblazer/cells-haml/blob/master/lib/cell/haml.rb#L5 and make the `:suffix` option configurable.

**Comment by jhblacklock** [comment]
Perfecto!  Thanks!

On Thu, Apr 14, 2016 at 7:24 PM, Nick Sutterer <notifications@github.com>
wrote:

> You might have to override
> https://github.com/trailblazer/cells-haml/blob/master/lib/cell/haml.rb#L5
> and make the :suffix option configurable.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/apotonick/cells/issues/390#issuecomment-210218601>
>



-- 
Check out Lodestone's Omni-Channel capabilities by viewing the following
quick video:
*OUR PLATFORM <http://youtu.be/yQaBppkuX5M>*
