### ISSUE TITLE
undefined method 'concept' and 'cell'

### ISSUE THREAD

**Issue by TrevorHinesley** [apotonick/cells#396]
Are the helpers gone in 4.1.0?

I'm getting:

`ActionView::Template::Error (undefined method `concept' for #<#<Class:0x007fa5fb126648>:0x007fa5f9d60398>)`

**Comment by Startouf** [comment]
I'm getting some weird error as well

`undefined method `builds' for TaskCell:Class`

`builds` as in `builds do |model|`

Seems like 4.1 needs some debugging :P

**Comment by apotonick** [comment]
The first point here: https://github.com/apotonick/cells/blob/master/CHANGES.md#api-fixchanges

**Comment by apotonick** [comment]
@TrevorHinesley Sorry - did you add the `cells-rails` gem?

**Comment by TrevorHinesley** [comment]
@apotonick no i wasn't

**Comment by apotonick** [comment]
https://github.com/apotonick/cells/blob/master/CHANGES.md#410
http://nicksda.apotomo.de/2016/05/cells-4-1-block-support-better-collections-external-layouts/

**Comment by TrevorHinesley** [comment]
Got it, thanks @apotonick

**Comment by apotonick** [comment]
:grin:
