### ISSUE TITLE
undefined method 'concept' in Cells 4.1.1

### ISSUE THREAD

**Issue by acaron** [apotonick/cells#398]
Cells 4.0.5 works fine, but I got `undefined method 'concept'` in my views with Cells 4.1.1. I don't see anywhere in the documentation about removing this before Cells 5?

**Comment by apotonick** [comment]
Please use `gem "cells-rails"', as noted here: https://github.com/apotonick/cells/blob/master/CHANGES.md#410 :giggle:

**Comment by acaron** [comment]
After adding `cells-rails` and updating `cells` to 4.1.1, I get one big problem...

app/concepts/auth/organization/cells/index.rb
```
class Auth::Organization::Cells::Index < Cell::Concept
  def show
    render :table
  end
end
```

I now get this error:
```
Template missing: view: `table.haml` prefixes: ["app/concepts/cells/views"]
```

**Comment by acaron** [comment]
P.S. This works, but I don't want to set them everywhere. Prefixes are no longer working by themselves...

`render view: :table, prefixes: ["app/concepts/auth/organization/cells/views"]`
