### ISSUE TITLE
Unable to access named routes in view

### ISSUE THREAD

**Issue by ericgross** [apotonick/cells#420]
I am rendering an HTML file from a cell in an application that mounts Spree as an engine. I want to access `spree.new_spree_user_session_path` but it is not defined in this context.

How can I access a mounted engine's named routes in my cell view?

**Comment by apotonick** [comment]
Pass the `spree` instance (whatever that is) into the cell.

```ruby
cell(:comment, @comment, spree: spree)
```

and use it via `options` in the cell! :wink:
