### ISSUE TITLE
SystemStackError: stack level too deep when rendering a view in a layout

### ISSUE THREAD

**Issue by AlexVPopov** [apotonick/cells#422]
Consider the following structure:

```
app
├── cells
│   ├── foo_cell.rb
│   ├── foo
│   │   ├── show.slim
│   │   ├── layout.slim
│   │   ├── bar.slim
```

```ruby
# foo_cell.rb

class FooCell < Cell::ViewModel
  include Cell::Slim
end
```

```ruby
# show.slim

.foo Hi
```

```ruby
# layout.slim

.layout
  = yield
```

```ruby
# bar.slim

.bar
```

Now consider the following additions and results:

* given the above setup:

```ruby
FooCell.new.() # => <div class="foo">Hi</div>
```
:+1: 
* if I add a layout to the FooCell like so:
```ruby
class FooCell < Cell::ViewModel
  include Cell::Slim
  layout :layout
end
```
then
```ruby
FooCell.new.() # => <div class="layout"><div class="foo">Hi</div></div>
```
:+1: 
* if I render a view within the `show` view of `FooCell` like so:
```ruby
# show.slim
.foo Hi
= render :bar
```
then
```ruby
FooCell.new.() # => <div class="layout"><div class="foo">Hi</div><div class="layout"><div class="bar"></div></div></div>
```
:-1: Why is the `bar` view in `show.slim` wrapped in a layout?
* finally, if I move the rendering of the `bar` view from `show.slim` to `layout.slim` like so:
```ruby
# layout.slim
.layout
  = yield
  = render :bar
```
then
```ruby
FooCell.new.() # =>
SystemStackError: stack level too deep
from /home/alex/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/temple-0.7.7/lib/temple/mixins/dispatcher.rb:65:in `dispatcher'
```
:-1: 
So why is every view of a cell wrapped in a layout and how do I use a layout only for the main view, but not for the nested views?

**Comment by AlexVPopov** [comment]
Based on [this issue](https://github.com/apotonick/cells/issues/314) the current workaround for me would be to remove the class-level declaration for the layout from FooCell (the `layout :layout` part on line 3) and put it in the `show` method:

```ruby
def show
  render layout: :layout
end
```

**Comment by apotonick** [comment]
Hi! Class-level layouts will be removed in Cells 5 in favor of the much more flexible runtime option, see the `:layout` option here: http://trailblazer.to/gems/cells/getting-started.html#putting-things-together

**Comment by AlexVPopov** [comment]
Hi and thanks for the quick resposne :+1:
