### ISSUE TITLE
Stacktrace is useless when an issue occurs

### ISSUE THREAD

**Issue by ericgross** [apotonick/cells#425]
I am using cells with a layout and lots of nested cells, and whenever something goes wrong, all I see in the stacktrace is my call:

```
def new
    render html: Survey::Cell::Show.call(nil,
                                         context: { current_user: current_spree_user },
                                         layout:  Home::Cell::Layout).call
  end

```

There is the message too (undefined method `url_options' for nil:NilClass) which can help, but overall this is a much worse experience than debugging a standard Rails view. Am I missing something?

**Comment by apotonick** [comment]
You don't pass the controller into the call. Please use the `cell` helper as documented here: http://trailblazer.to/gems/cells/api.html#instantiation-helper This helper will inject the controller for you and then `url_for` and friends work.

I'm not sure I understand the stacktrace problem, could you paste your exception (or maybe the first 10 lines)?
