### ISSUE TITLE
Cells::Rails::ActionController methods not available in ActionController::Caching::Sweeper

### ISSUE THREAD

**Issue by fractious** [apotonick/cells#63]
Given this sweeper:

```ruby
class UserSweeper < ActionController::Caching::Sweeper
  observe User

  def after_update(user)
    Rails.logger.debug Rails.cache.instance_variable_get(:@data).keys.inspect
    expire_cell_state HeaderCell, :show
    Rails.logger.debug Rails.cache.instance_variable_get(:@data).keys.inspect
  end

end
```

when `#after_update` is called the `HeaderCell` cache key isn't being deleted as expected. No errors are raised.

Firing up the debugger reveals that we are hitting [`ActionController::Caching::Sweeping#method_missing`](https://github.com/rails/rails/blob/v3.0.9/actionpack/lib/action_controller/caching/sweeping.rb#L89) with `@controller` equal to `nil` and so being silently returned.

A simple `include Cells::Rails::ActionController` in the Sweeper fixes this but I'm left wondering why it's not being properly mixed in without this.

ree-1.8.7-2011.03, rails 3.0.9, cells 3.6.4.

**Comment by apotonick** [comment]
We don't sweep in Cells 4 anymore, soooorry.
