### ISSUE TITLE
Cycle helper not working inside cell

### ISSUE THREAD

**Issue by kelso** [apotonick/cells#75]
# How to reproduce

app/views/categories/show.html.haml

    - @books.each do |book|
      = render_cell :book, :display, :book => book

app/cells/book/display.html.haml

    %p{:class => cycle => "odd", "even"}
      = @book.name

# Result

Resulted html source is wrong:

    <p class="odd">...</p>
    <p class="odd">...</p>
    <p class="odd">...</p>
    <p class="odd">...</p>

Right code would be:

    <p class="odd">...</p>
    <p class="even">...</p>
    <p class="odd">...</p>
    <p class="even">...</p>

**Comment by apotonick** [comment]
The `cycle` helper is not supported as it relies on global state. In Cells 4.1, this can be easily solved by injecting the index. See http://trailblazer.to/gems/cells/api.html#collection
