### ISSUE TITLE
View Inheritance skips classes in between

### ISSUE THREAD

**Issue by KevinTriplett** [apotonick/cells#77]
Great gem, thanks Nick I use cells and apotomo as often as I can!

I'm trying out the new inheritance and if I have the following:

    class SearchWidget < Apotomo::Widget
    end

    class InventoryItemSearchWidget < SearchWidget
    end

    class AssetSearchWidget < InventoryItemSearchWidget
    end

and I have the views:

    asset_search/display.html.haml
    inventory_item_search/table.html.haml
    search/table.html.haml
    search/display.html.haml

and in asset_search/display.html.haml:

    = render :view => :table

I get the search/table.html.haml, not inventory_item_search/table.html.haml as expected. This is probably a Rails 3.1 bug (which my app is running).

Thanks again for all your hard work and brilliant contributions!

**Comment by apotonick** [comment]
This does not happen in Cells 4. :tongue: :stuck_out_tongue_winking_eye:
